// 1000 most-used German words — Groups 1-5 (100 each)
const SETS = {

"G1 — Core Phrases":[
{de:"Hallo",ph:"HAL-loh",en:"Hello",s:"Hallo, ich bin Thomas.",t:"Hello, I am Thomas."},
{de:"Tschüss",ph:"CHYOOS",en:"Bye (informal)",s:"Tschüss, bis morgen!",t:"Bye, see you tomorrow!"},
{de:"Guten Morgen",ph:"GOO-ten MOR-gen",en:"Good morning",s:"Guten Morgen, wie geht es dir?",t:"Good morning, how are you?"},
{de:"Guten Tag",ph:"GOO-ten TAHG",en:"Good day",s:"Guten Tag, kann ich helfen?",t:"Good day, can I help?"},
{de:"Guten Abend",ph:"GOO-ten AH-bent",en:"Good evening",s:"Guten Abend, alle zusammen!",t:"Good evening, everyone!"},
{de:"Gute Nacht",ph:"GOO-teh NAKHT",en:"Good night",s:"Gute Nacht, schlaf gut!",t:"Good night, sleep well!"},
{de:"Willkommen",ph:"vil-KOM-en",en:"Welcome",s:"Willkommen in Deutschland!",t:"Welcome to Germany!"},
{de:"Auf Wiedersehen",ph:"owf VEE-der-zayn",en:"Goodbye (formal)",s:"Auf Wiedersehen bis nächste Woche.",t:"Goodbye until next week."},
{de:"Bis bald",ph:"BIS bahlt",en:"See you soon",s:"Bis bald, mein Freund!",t:"See you soon, my friend!"},
{de:"Bis später",ph:"BIS SHPAY-ter",en:"See you later",s:"Bis später, ich muss jetzt gehen.",t:"See you later, I must go now."},
{de:"Danke",ph:"DAHN-keh",en:"Thank you",s:"Danke für deine Hilfe.",t:"Thank you for your help."},
{de:"Danke schön",ph:"DAHN-keh SHUN",en:"Thank you very much",s:"Danke schön für das Geschenk.",t:"Thank you very much for the gift."},
{de:"Bitte",ph:"BIT-teh",en:"Please / You're welcome",s:"Bitte gib mir das Buch.",t:"Please give me the book."},
{de:"Entschuldigung",ph:"ent-SHOOL-dih-goong",en:"Excuse me / Sorry",s:"Entschuldigung, wo ist der Bahnhof?",t:"Excuse me, where is the station?"},
{de:"Es tut mir leid",ph:"es TOOT meer lyed",en:"I am sorry",s:"Es tut mir leid, das war mein Fehler.",t:"I am sorry, that was my mistake."},
{de:"Kein Problem",ph:"KINE pro-BLAYM",en:"No problem",s:"Kein Problem, ich helfe gern.",t:"No problem, I am happy to help."},
{de:"Ja",ph:"YAH",en:"Yes",s:"Ja, ich verstehe das.",t:"Yes, I understand that."},
{de:"Nein",ph:"NINE",en:"No",s:"Nein, das ist nicht richtig.",t:"No, that is not correct."},
{de:"Vielleicht",ph:"fee-LYSHT",en:"Maybe / Perhaps",s:"Vielleicht komme ich morgen.",t:"Maybe I will come tomorrow."},
{de:"Natürlich",ph:"nah-TYOOR-lish",en:"Of course",s:"Natürlich helfe ich dir.",t:"Of course I will help you."},
{de:"ich",ph:"ISH",en:"I / me",s:"Ich lerne jeden Tag Deutsch.",t:"I learn German every day."},
{de:"du",ph:"DOO",en:"you (informal)",s:"Du bist sehr freundlich.",t:"You are very friendly."},
{de:"er",ph:"EHR",en:"he",s:"Er kommt morgen Abend.",t:"He is coming tomorrow evening."},
{de:"sie",ph:"ZEE",en:"she / they / you (formal)",s:"Sie liest gern Bücher.",t:"She likes reading books."},
{de:"es",ph:"ES",en:"it",s:"Es ist heute sehr kalt.",t:"It is very cold today."},
{de:"wir",ph:"VEER",en:"we",s:"Wir gehen zusammen ins Kino.",t:"We are going to the cinema together."},
{de:"ihr",ph:"EER",en:"you (plural informal)",s:"Seid ihr alle bereit?",t:"Are you all ready?"},
{de:"man",ph:"MAHN",en:"one / you (general)",s:"Man lernt nie aus.",t:"One never stops learning."},
{de:"was",ph:"VAHS",en:"what",s:"Was machst du heute?",t:"What are you doing today?"},
{de:"wo",ph:"VOH",en:"where",s:"Wo wohnst du gerade?",t:"Where do you live right now?"},
{de:"wer",ph:"VEHR",en:"who",s:"Wer ist dieses Mädchen?",t:"Who is this girl?"},
{de:"wann",ph:"VAHN",en:"when",s:"Wann fährt der nächste Zug?",t:"When does the next train leave?"},
{de:"warum",ph:"vah-ROOM",en:"why",s:"Warum bist du so traurig?",t:"Why are you so sad?"},
{de:"wie",ph:"VEE",en:"how",s:"Wie geht es dir heute?",t:"How are you today?"},
{de:"welcher",ph:"VEL-sher",en:"which",s:"Welcher Bus fährt ins Zentrum?",t:"Which bus goes to the centre?"},
{de:"wohin",ph:"voh-HIN",en:"where to",s:"Wohin gehst du jetzt?",t:"Where are you going now?"},
{de:"woher",ph:"voh-HEHR",en:"where from",s:"Woher kommst du ursprünglich?",t:"Where do you originally come from?"},
{de:"wie viel",ph:"VEE feel",en:"how much / how many",s:"Wie viel kostet das Ticket?",t:"How much does the ticket cost?"},
{de:"und",ph:"OONT",en:"and",s:"Ich mag Kaffee und Tee.",t:"I like coffee and tea."},
{de:"oder",ph:"OH-der",en:"or",s:"Kaffee oder Tee, was magst du?",t:"Coffee or tea, what do you like?"},
{de:"aber",ph:"AH-ber",en:"but",s:"Es ist schön, aber teuer.",t:"It is nice but expensive."},
{de:"weil",ph:"VYL",en:"because",s:"Ich bleibe, weil es regnet.",t:"I am staying because it is raining."},
{de:"wenn",ph:"VEN",en:"when / if",s:"Wenn ich Zeit habe, komme ich.",t:"If I have time, I will come."},
{de:"dass",ph:"DAHS",en:"that (conjunction)",s:"Ich glaube, dass er kommt.",t:"I believe that he is coming."},
{de:"obwohl",ph:"ob-VOHL",en:"although",s:"Obwohl es spät ist, arbeite ich.",t:"Although it is late, I am working."},
{de:"also",ph:"AHL-zo",en:"so / therefore",s:"Es regnet, also bleibe ich.",t:"It is raining, so I am staying."},
{de:"denn",ph:"DEN",en:"because / for",s:"Ich gehe, denn ich bin müde.",t:"I am leaving because I am tired."},
{de:"trotzdem",ph:"TROTS-dem",en:"nevertheless",s:"Es regnet, trotzdem gehe ich.",t:"It is raining, nevertheless I am going."},
{de:"sondern",ph:"ZON-dern",en:"but rather",s:"Nicht er, sondern sie hat gewonnen.",t:"Not he but rather she won."},
{de:"nicht",ph:"NISHT",en:"not",s:"Ich verstehe das nicht.",t:"I do not understand that."},
{de:"kein",ph:"KINE",en:"no / not a",s:"Ich habe kein Geld dabei.",t:"I have no money on me."},
{de:"sehr",ph:"ZEHR",en:"very",s:"Das Essen ist sehr lecker.",t:"The food is very delicious."},
{de:"auch",ph:"OWKH",en:"also / too",s:"Ich komme auch zur Party.",t:"I am also coming to the party."},
{de:"noch",ph:"NOKH",en:"still / yet",s:"Ich bin noch nicht fertig.",t:"I am not finished yet."},
{de:"schon",ph:"SHOHN",en:"already",s:"Er ist schon nach Hause gegangen.",t:"He has already gone home."},
{de:"nur",ph:"NOOR",en:"only / just",s:"Ich habe nur fünf Minuten.",t:"I only have five minutes."},
{de:"immer",ph:"IM-er",en:"always",s:"Er ist immer pünktlich.",t:"He is always punctual."},
{de:"nie",ph:"NEE",en:"never",s:"Ich bin nie in Paris gewesen.",t:"I have never been to Paris."},
{de:"manchmal",ph:"MANSH-mahl",en:"sometimes",s:"Manchmal gehe ich spazieren.",t:"Sometimes I go for a walk."},
{de:"oft",ph:"OFT",en:"often",s:"Ich trinke oft Kaffee.",t:"I often drink coffee."},
{de:"jetzt",ph:"YETST",en:"now",s:"Ich muss jetzt sofort gehen.",t:"I have to go right now."},
{de:"dann",ph:"DAHN",en:"then",s:"Zuerst essen, dann Hausaufgaben machen.",t:"First eat, then do homework."},
{de:"hier",ph:"HEER",en:"here",s:"Komm bitte hier zu mir.",t:"Please come here to me."},
{de:"da",ph:"DAH",en:"there / here",s:"Er ist da drüben.",t:"He is over there."},
{de:"dort",ph:"DORT",en:"over there",s:"Das Restaurant ist dort rechts.",t:"The restaurant is over there on the right."},
{de:"links",ph:"LINKS",en:"left",s:"Bieg bitte links ab.",t:"Please turn left."},
{de:"rechts",ph:"RESHTS",en:"right",s:"Die Bank ist rechts.",t:"The bank is on the right."},
{de:"oben",ph:"OH-ben",en:"above / upstairs",s:"Das Buch liegt oben auf dem Regal.",t:"The book is at the top of the shelf."},
{de:"unten",ph:"OON-ten",en:"below / downstairs",s:"Die Küche ist unten.",t:"The kitchen is downstairs."},
{de:"vorne",ph:"FOR-neh",en:"in front / at the front",s:"Setz dich vorne hin.",t:"Sit down at the front."},
{de:"hinten",ph:"HIN-ten",en:"at the back / behind",s:"Er sitzt hinten im Bus.",t:"He sits at the back of the bus."},
{de:"heute",ph:"HOY-teh",en:"today",s:"Heute ist ein schöner Tag.",t:"Today is a beautiful day."},
{de:"morgen",ph:"MOR-gen",en:"tomorrow / morning",s:"Morgen fliege ich nach Berlin.",t:"Tomorrow I fly to Berlin."},
{de:"gestern",ph:"GES-tern",en:"yesterday",s:"Gestern war das Wetter schlecht.",t:"Yesterday the weather was bad."},
{de:"früher",ph:"FRYOO-er",en:"earlier / formerly",s:"Früher war hier ein Park.",t:"There used to be a park here."},
{de:"später",ph:"SHPAY-ter",en:"later",s:"Wir sehen uns später.",t:"We will see each other later."},
{de:"gut",ph:"GOOT",en:"good / well",s:"Das Essen schmeckt sehr gut.",t:"The food tastes very good."},
{de:"schlecht",ph:"SHLEKHT",en:"bad",s:"Das Wetter ist heute schlecht.",t:"The weather is bad today."},
{de:"groß",ph:"GROHS",en:"big / tall",s:"Er ist sehr groß und stark.",t:"He is very tall and strong."},
{de:"klein",ph:"KLINE",en:"small / little",s:"Das ist ein kleines Problem.",t:"That is a small problem."},
{de:"alles",ph:"AHL-es",en:"everything",s:"Alles ist möglich mit Übung.",t:"Everything is possible with practice."},
{de:"nichts",ph:"NISHTS",en:"nothing",s:"Ich habe nichts gegessen heute.",t:"I have not eaten anything today."},
{de:"etwas",ph:"ET-vahs",en:"something / a little",s:"Kann ich etwas fragen?",t:"Can I ask something?"},
{de:"jemand",ph:"YAY-mahnt",en:"someone",s:"Jemand klopft an die Tür.",t:"Someone is knocking at the door."},
{de:"niemand",ph:"NEE-mahnt",en:"nobody",s:"Niemand war zu Hause.",t:"Nobody was at home."},
{de:"viel",ph:"FEEL",en:"much / a lot",s:"Ich habe viel zu tun.",t:"I have a lot to do."},
{de:"wenig",ph:"VAY-nig",en:"little / few",s:"Ich habe wenig Zeit heute.",t:"I have little time today."},
{de:"mehr",ph:"MEHR",en:"more",s:"Ich möchte mehr Wasser trinken.",t:"I would like to drink more water."},
{de:"alle",ph:"AHL-eh",en:"all / everyone",s:"Alle Schüler sind da.",t:"All students are present."},
{de:"beide",ph:"BY-deh",en:"both",s:"Beide Antworten sind richtig.",t:"Both answers are correct."},
{de:"Freut mich",ph:"FROYT mish",en:"Nice to meet you",s:"Freut mich, Sie kennenzulernen.",t:"Nice to meet you."},
{de:"Wie bitte?",ph:"VEE BIT-teh",en:"Pardon? / Come again?",s:"Wie bitte? Ich habe nicht verstanden.",t:"Pardon? I did not understand."},
{de:"Ich weiß nicht",ph:"ISH VYS nisht",en:"I don't know",s:"Ich weiß nicht, wo er ist.",t:"I do not know where he is."},
{de:"Ich verstehe",ph:"ISH fer-SHTAY-eh",en:"I understand",s:"Ich verstehe die Aufgabe jetzt.",t:"I understand the task now."},
{de:"Ich heiße",ph:"ISH HY-seh",en:"My name is",s:"Ich heiße Thomas. Und du?",t:"My name is Thomas. And you?"},
{de:"Ich komme aus",ph:"ISH KOM-eh OWS",en:"I come from",s:"Ich komme aus Bangladesh.",t:"I come from Bangladesh."},
{de:"Ich möchte",ph:"ISH MUKH-teh",en:"I would like",s:"Ich möchte einen Kaffee bitte.",t:"I would like a coffee please."},
{de:"Es geht mir gut",ph:"es GAYT meer goot",en:"I am doing well",s:"Danke, es geht mir gut.",t:"Thank you, I am doing well."},
{de:"Alles klar",ph:"AHL-es KLAHR",en:"Got it / All good / OK",s:"Alles klar, ich mache das.",t:"Got it, I will do that."},
{de:"Keine Ahnung",ph:"KY-neh AH-noong",en:"No idea / No clue",s:"Keine Ahnung, frag mal Thomas.",t:"No idea, ask Thomas."}
]

}; // G2-G10 loaded by words2.js and words3.js
