// 1000 most-used German words — 10 groups × 100
const SETS = {

"G1 — Core Phrases":[
{de:"Hallo",ph:"HAL-loh",en:"Hello",s:"Hallo, ich bin Thomas.",t:"Hello, I am Thomas."},
{de:"Tschüss",ph:"CHYOOS",en:"Bye (informal)",s:"Tschüss, bis morgen!",t:"Bye, see you tomorrow!"},
{de:"Guten Morgen",ph:"GOO-ten MOR-gen",en:"Good morning",s:"Guten Morgen, wie geht es dir?",t:"Good morning, how are you?"},
{de:"Guten Tag",ph:"GOO-ten TAHG",en:"Good day",s:"Guten Tag, kann ich helfen?",t:"Good day, can I help?"},
{de:"Guten Abend",ph:"GOO-ten AH-bent",en:"Good evening",s:"Guten Abend, alle zusammen!",t:"Good evening, everyone!"},
{de:"Gute Nacht",ph:"GOO-teh NAKHT",en:"Good night",s:"Gute Nacht, schlaf gut!",t:"Good night, sleep well!"},
{de:"Willkommen",ph:"vil-KOM-en",en:"Welcome",s:"Willkommen in Deutschland!",t:"Welcome to Germany!"},
{de:"Auf Wiedersehen",ph:"owf VEE-der-zayn",en:"Goodbye (formal)",s:"Auf Wiedersehen bis nächste Woche.",t:"Goodbye until next week."},
{de:"Bis bald",ph:"BIS bahlt",en:"See you soon",s:"Bis bald, mein Freund!",t:"See you soon, my friend!"},
{de:"Bis später",ph:"BIS SHPAY-ter",en:"See you later",s:"Bis später, ich muss jetzt gehen.",t:"See you later, I must go now."},
{de:"Danke",ph:"DAHN-keh",en:"Thank you",s:"Danke für deine Hilfe.",t:"Thank you for your help."},
{de:"Danke schön",ph:"DAHN-keh SHUN",en:"Thank you very much",s:"Danke schön für das Geschenk.",t:"Thank you very much for the gift."},
{de:"Bitte",ph:"BIT-teh",en:"Please / You're welcome",s:"Bitte gib mir das Buch.",t:"Please give me the book."},
{de:"Entschuldigung",ph:"ent-SHOOL-dih-goong",en:"Excuse me / Sorry",s:"Entschuldigung, wo ist der Bahnhof?",t:"Excuse me, where is the station?"},
{de:"Es tut mir leid",ph:"es TOOT meer lyed",en:"I am sorry",s:"Es tut mir leid, das war mein Fehler.",t:"I am sorry, that was my mistake."},
{de:"Kein Problem",ph:"KINE pro-BLAYM",en:"No problem",s:"Kein Problem, ich helfe gern.",t:"No problem, I am happy to help."},
{de:"Ja",ph:"YAH",en:"Yes",s:"Ja, ich verstehe das.",t:"Yes, I understand that."},
{de:"Nein",ph:"NINE",en:"No",s:"Nein, das ist nicht richtig.",t:"No, that is not correct."},
{de:"Vielleicht",ph:"fee-LYSHT",en:"Maybe / Perhaps",s:"Vielleicht komme ich morgen.",t:"Maybe I will come tomorrow."},
{de:"Natürlich",ph:"nah-TYOOR-lish",en:"Of course",s:"Natürlich helfe ich dir.",t:"Of course I will help you."},
{de:"ich",ph:"ISH",en:"I / me",s:"Ich lerne jeden Tag Deutsch.",t:"I learn German every day."},
{de:"du",ph:"DOO",en:"you (informal)",s:"Du bist sehr freundlich.",t:"You are very friendly."},
{de:"er",ph:"EHR",en:"he",s:"Er kommt morgen Abend.",t:"He is coming tomorrow evening."},
{de:"sie",ph:"ZEE",en:"she / they / you (formal)",s:"Sie liest gern Bücher.",t:"She likes reading books."},
{de:"es",ph:"ES",en:"it",s:"Es ist heute sehr kalt.",t:"It is very cold today."},
{de:"wir",ph:"VEER",en:"we",s:"Wir gehen zusammen ins Kino.",t:"We are going to the cinema together."},
{de:"ihr",ph:"EER",en:"you (plural informal)",s:"Seid ihr alle bereit?",t:"Are you all ready?"},
{de:"man",ph:"MAHN",en:"one / you (general)",s:"Man lernt nie aus.",t:"One never stops learning."},
{de:"was",ph:"VAHS",en:"what",s:"Was machst du heute?",t:"What are you doing today?"},
{de:"wo",ph:"VOH",en:"where",s:"Wo wohnst du gerade?",t:"Where do you live right now?"},
{de:"wer",ph:"VEHR",en:"who",s:"Wer ist dieses Mädchen?",t:"Who is this girl?"},
{de:"wann",ph:"VAHN",en:"when",s:"Wann fährt der nächste Zug?",t:"When does the next train leave?"},
{de:"warum",ph:"vah-ROOM",en:"why",s:"Warum bist du so traurig?",t:"Why are you so sad?"},
{de:"wie",ph:"VEE",en:"how",s:"Wie geht es dir heute?",t:"How are you today?"},
{de:"welcher",ph:"VEL-sher",en:"which",s:"Welcher Bus fährt ins Zentrum?",t:"Which bus goes to the centre?"},
{de:"wohin",ph:"voh-HIN",en:"where to",s:"Wohin gehst du jetzt?",t:"Where are you going now?"},
{de:"woher",ph:"voh-HEHR",en:"where from",s:"Woher kommst du ursprünglich?",t:"Where do you originally come from?"},
{de:"wie viel",ph:"VEE feel",en:"how much / how many",s:"Wie viel kostet das Ticket?",t:"How much does the ticket cost?"},
{de:"und",ph:"OONT",en:"and",s:"Ich mag Kaffee und Tee.",t:"I like coffee and tea."},
{de:"oder",ph:"OH-der",en:"or",s:"Kaffee oder Tee, was magst du?",t:"Coffee or tea, what do you like?"},
{de:"aber",ph:"AH-ber",en:"but",s:"Es ist schön, aber teuer.",t:"It is nice but expensive."},
{de:"weil",ph:"VYL",en:"because",s:"Ich bleibe, weil es regnet.",t:"I am staying because it is raining."},
{de:"wenn",ph:"VEN",en:"when / if",s:"Wenn ich Zeit habe, komme ich.",t:"If I have time, I will come."},
{de:"dass",ph:"DAHS",en:"that (conjunction)",s:"Ich glaube, dass er kommt.",t:"I believe that he is coming."},
{de:"obwohl",ph:"ob-VOHL",en:"although",s:"Obwohl es spät ist, arbeite ich.",t:"Although it is late, I am working."},
{de:"also",ph:"AHL-zo",en:"so / therefore",s:"Es regnet, also bleibe ich.",t:"It is raining, so I am staying."},
{de:"denn",ph:"DEN",en:"because / for",s:"Ich gehe, denn ich bin müde.",t:"I am leaving because I am tired."},
{de:"trotzdem",ph:"TROTS-dem",en:"nevertheless",s:"Es regnet, trotzdem gehe ich.",t:"It is raining, nevertheless I am going."},
{de:"sondern",ph:"ZON-dern",en:"but rather",s:"Nicht er, sondern sie hat gewonnen.",t:"Not he but rather she won."},
{de:"nicht",ph:"NISHT",en:"not",s:"Ich verstehe das nicht.",t:"I do not understand that."},
{de:"kein",ph:"KINE",en:"no / not a",s:"Ich habe kein Geld dabei.",t:"I have no money on me."},
{de:"sehr",ph:"ZEHR",en:"very",s:"Das Essen ist sehr lecker.",t:"The food is very delicious."},
{de:"auch",ph:"OWKH",en:"also / too",s:"Ich komme auch zur Party.",t:"I am also coming to the party."},
{de:"noch",ph:"NOKH",en:"still / yet",s:"Ich bin noch nicht fertig.",t:"I am not finished yet."},
{de:"schon",ph:"SHOHN",en:"already",s:"Er ist schon nach Hause gegangen.",t:"He has already gone home."},
{de:"nur",ph:"NOOR",en:"only / just",s:"Ich habe nur fünf Minuten.",t:"I only have five minutes."},
{de:"immer",ph:"IM-er",en:"always",s:"Er ist immer pünktlich.",t:"He is always punctual."},
{de:"nie",ph:"NEE",en:"never",s:"Ich bin nie in Paris gewesen.",t:"I have never been to Paris."},
{de:"manchmal",ph:"MANSH-mahl",en:"sometimes",s:"Manchmal gehe ich spazieren.",t:"Sometimes I go for a walk."},
{de:"oft",ph:"OFT",en:"often",s:"Ich trinke oft Kaffee.",t:"I often drink coffee."},
{de:"jetzt",ph:"YETST",en:"now",s:"Ich muss jetzt sofort gehen.",t:"I have to go right now."},
{de:"dann",ph:"DAHN",en:"then",s:"Zuerst essen, dann Hausaufgaben machen.",t:"First eat, then do homework."},
{de:"hier",ph:"HEER",en:"here",s:"Komm bitte hier zu mir.",t:"Please come here to me."},
{de:"da",ph:"DAH",en:"there / here",s:"Er ist da drüben.",t:"He is over there."},
{de:"dort",ph:"DORT",en:"over there",s:"Das Restaurant ist dort rechts.",t:"The restaurant is over there on the right."},
{de:"links",ph:"LINKS",en:"left",s:"Bieg bitte links ab.",t:"Please turn left."},
{de:"rechts",ph:"RESHTS",en:"right",s:"Die Bank ist rechts.",t:"The bank is on the right."},
{de:"oben",ph:"OH-ben",en:"above / upstairs",s:"Das Buch liegt oben auf dem Regal.",t:"The book is at the top of the shelf."},
{de:"unten",ph:"OON-ten",en:"below / downstairs",s:"Die Küche ist unten.",t:"The kitchen is downstairs."},
{de:"vorne",ph:"FOR-neh",en:"in front / at the front",s:"Setz dich vorne hin.",t:"Sit down at the front."},
{de:"hinten",ph:"HIN-ten",en:"at the back / behind",s:"Er sitzt hinten im Bus.",t:"He sits at the back of the bus."},
{de:"heute",ph:"HOY-teh",en:"today",s:"Heute ist ein schöner Tag.",t:"Today is a beautiful day."},
{de:"morgen",ph:"MOR-gen",en:"tomorrow / morning",s:"Morgen fliege ich nach Berlin.",t:"Tomorrow I fly to Berlin."},
{de:"gestern",ph:"GES-tern",en:"yesterday",s:"Gestern war das Wetter schlecht.",t:"Yesterday the weather was bad."},
{de:"früher",ph:"FRYOO-er",en:"earlier / formerly",s:"Früher war hier ein Park.",t:"There used to be a park here."},
{de:"später",ph:"SHPAY-ter",en:"later",s:"Wir sehen uns später.",t:"We will see each other later."},
{de:"gut",ph:"GOOT",en:"good / well",s:"Das Essen schmeckt sehr gut.",t:"The food tastes very good."},
{de:"schlecht",ph:"SHLEKHT",en:"bad",s:"Das Wetter ist heute schlecht.",t:"The weather is bad today."},
{de:"groß",ph:"GROHS",en:"big / tall",s:"Er ist sehr groß und stark.",t:"He is very tall and strong."},
{de:"klein",ph:"KLINE",en:"small / little",s:"Das ist ein kleines Problem.",t:"That is a small problem."},
{de:"alles",ph:"AHL-es",en:"everything",s:"Alles ist möglich mit Übung.",t:"Everything is possible with practice."},
{de:"nichts",ph:"NISHTS",en:"nothing",s:"Ich habe nichts gegessen heute.",t:"I have not eaten anything today."},
{de:"etwas",ph:"ET-vahs",en:"something / a little",s:"Kann ich etwas fragen?",t:"Can I ask something?"},
{de:"jemand",ph:"YAY-mahnt",en:"someone",s:"Jemand klopft an die Tür.",t:"Someone is knocking at the door."},
{de:"niemand",ph:"NEE-mahnt",en:"nobody",s:"Niemand war zu Hause.",t:"Nobody was at home."},
{de:"viel",ph:"FEEL",en:"much / a lot",s:"Ich habe viel zu tun.",t:"I have a lot to do."},
{de:"wenig",ph:"VAY-nig",en:"little / few",s:"Ich habe wenig Zeit heute.",t:"I have little time today."},
{de:"mehr",ph:"MEHR",en:"more",s:"Ich möchte mehr Wasser trinken.",t:"I would like to drink more water."},
{de:"alle",ph:"AHL-eh",en:"all / everyone",s:"Alle Schüler sind da.",t:"All students are present."},
{de:"beide",ph:"BY-deh",en:"both",s:"Beide Antworten sind richtig.",t:"Both answers are correct."},
{de:"Freut mich",ph:"FROYT mish",en:"Nice to meet you",s:"Freut mich, Sie kennenzulernen.",t:"Nice to meet you."},
{de:"Wie bitte?",ph:"VEE BIT-teh",en:"Pardon? / Come again?",s:"Wie bitte? Ich habe nicht verstanden.",t:"Pardon? I did not understand."},
{de:"Ich weiß nicht",ph:"ISH VYS nisht",en:"I don't know",s:"Ich weiß nicht, wo er ist.",t:"I do not know where he is."},
{de:"Ich verstehe",ph:"ISH fer-SHTAY-eh",en:"I understand",s:"Ich verstehe die Aufgabe jetzt.",t:"I understand the task now."},
{de:"Ich heiße",ph:"ISH HY-seh",en:"My name is",s:"Ich heiße Thomas. Und du?",t:"My name is Thomas. And you?"},
{de:"Ich komme aus",ph:"ISH KOM-eh OWS",en:"I come from",s:"Ich komme aus Bangladesh.",t:"I come from Bangladesh."},
{de:"Ich möchte",ph:"ISH MUKH-teh",en:"I would like",s:"Ich möchte einen Kaffee bitte.",t:"I would like a coffee please."},
{de:"Es geht mir gut",ph:"es GAYT meer goot",en:"I am doing well",s:"Danke, es geht mir gut.",t:"Thank you, I am doing well."},
{de:"Alles klar",ph:"AHL-es KLAHR",en:"Got it / All good / OK",s:"Alles klar, ich mache das.",t:"Got it, I will do that."},
{de:"Keine Ahnung",ph:"KY-neh AH-noong",en:"No idea / No clue",s:"Keine Ahnung, frag mal Thomas.",t:"No idea, ask Thomas."}
],

"G2 — Core Verbs":[
{de:"sein",ph:"ZINE",en:"to be",s:"Ich muss sein bestes geben.",t:"I must give my best."},
{de:"haben",ph:"HAH-ben",en:"to have",s:"Ich habe Hunger.",t:"I am hungry."},
{de:"werden",ph:"VEHR-den",en:"to become / will (future)",s:"Es wird bald kalt.",t:"It will soon be cold."},
{de:"können",ph:"KUN-en",en:"can / to be able to",s:"Ich kann gut schwimmen.",t:"I can swim well."},
{de:"müssen",ph:"MUE-sen",en:"must / to have to",s:"Ich muss früh aufstehen.",t:"I must get up early."},
{de:"wollen",ph:"VOL-en",en:"to want",s:"Ich will Deutsch lernen.",t:"I want to learn German."},
{de:"sollen",ph:"ZOL-en",en:"should / supposed to",s:"Du sollst pünktlich sein.",t:"You should be punctual."},
{de:"dürfen",ph:"DUHR-fen",en:"may / to be allowed",s:"Darf ich eine Frage stellen?",t:"May I ask a question?"},
{de:"mögen",ph:"MUH-gen",en:"to like",s:"Ich mag Schokolade sehr.",t:"I like chocolate very much."},
{de:"möchten",ph:"MUKH-ten",en:"would like",s:"Ich möchte Kaffee bitte.",t:"I would like coffee please."},
{de:"gehen",ph:"GAY-en",en:"to go / to walk",s:"Ich gehe morgen zur Schule.",t:"I am going to school tomorrow."},
{de:"kommen",ph:"KOM-en",en:"to come",s:"Er kommt gleich nach Hause.",t:"He is coming home soon."},
{de:"fahren",ph:"FAH-ren",en:"to drive / to travel",s:"Wir fahren morgen nach Berlin.",t:"We are driving to Berlin tomorrow."},
{de:"fliegen",ph:"FLEE-gen",en:"to fly",s:"Ich fliege nächste Woche nach Amerika.",t:"I am flying to America next week."},
{de:"laufen",ph:"LOW-fen",en:"to run / to walk",s:"Er läuft jeden Morgen laufen.",t:"He goes for a run every morning."},
{de:"bleiben",ph:"BLY-ben",en:"to stay / to remain",s:"Ich bleibe heute zu Hause.",t:"I am staying at home today."},
{de:"stehen",ph:"SHTAY-en",en:"to stand",s:"Er muss lange stehen.",t:"He has to stand for a long time."},
{de:"sitzen",ph:"ZIT-sen",en:"to sit",s:"Ich möchte vorne sitzen.",t:"I would like to sit at the front."},
{de:"liegen",ph:"LEE-gen",en:"to lie / to be located",s:"Das Buch muss hier liegen.",t:"The book must be lying here."},
{de:"nehmen",ph:"NAY-men",en:"to take",s:"Ich will den Bus nehmen.",t:"I want to take the bus."},
{de:"geben",ph:"GAY-ben",en:"to give",s:"Kann er mir das Buch geben?",t:"Can he give me the book?"},
{de:"bringen",ph:"BRING-en",en:"to bring",s:"Kannst du mir Wasser bringen?",t:"Can you bring me some water?"},
{de:"holen",ph:"HOH-len",en:"to get / to fetch",s:"Ich muss Brot holen.",t:"I need to get some bread."},
{de:"lassen",ph:"LAHS-en",en:"to let / to leave",s:"Lass mich bitte in Ruhe!",t:"Please leave me alone!"},
{de:"halten",ph:"HAHL-ten",en:"to hold / to stop",s:"Der Bus wird hier halten.",t:"The bus will stop here."},
{de:"stellen",ph:"SHTEL-en",en:"to put (upright)",s:"Bitte die Flasche auf den Tisch stellen.",t:"Please put the bottle on the table."},
{de:"legen",ph:"LAY-gen",en:"to lay / put (flat)",s:"Er muss das Buch hinlegen.",t:"He needs to put the book down."},
{de:"öffnen",ph:"UHF-nen",en:"to open",s:"Kannst du die Tür öffnen?",t:"Can you open the door?"},
{de:"schließen",ph:"SHLEE-sen",en:"to close",s:"Bitte das Fenster schließen.",t:"Please close the window."},
{de:"beginnen",ph:"beh-GIN-en",en:"to begin / start",s:"Der Film wird um 8 beginnen.",t:"The film will begin at 8."},
{de:"enden",ph:"EN-den",en:"to end / finish",s:"Wann soll die Schule enden?",t:"When should school end?"},
{de:"warten",ph:"VAHR-ten",en:"to wait",s:"Ich muss auf den Bus warten.",t:"I have to wait for the bus."},
{de:"suchen",ph:"ZOO-khen",en:"to look for / search",s:"Ich muss meine Brille suchen.",t:"I need to look for my glasses."},
{de:"finden",ph:"FIN-den",en:"to find",s:"Ich kann den Schlüssel nicht finden.",t:"I cannot find the key."},
{de:"verlieren",ph:"fehr-LEER-en",en:"to lose",s:"Ich darf mein Handy nicht verlieren.",t:"I must not lose my phone."},
{de:"gewinnen",ph:"geh-VIN-en",en:"to win",s:"Wir wollen das Spiel gewinnen!",t:"We want to win the game!"},
{de:"sehen",ph:"ZAY-en",en:"to see",s:"Ich kann das Haus sehen.",t:"I can see the house."},
{de:"schauen",ph:"SHOW-en",en:"to look / to watch",s:"Ich will fernsehen schauen.",t:"I want to watch TV."},
{de:"hören",ph:"HUH-ren",en:"to hear / to listen",s:"Ich mag Musik hören.",t:"I like listening to music."},
{de:"fühlen",ph:"FUE-len",en:"to feel",s:"Ich fühle mich heute krank.",t:"I feel sick today."},
{de:"riechen",ph:"REE-khen",en:"to smell",s:"Das Essen riecht gut.",t:"The food smells good."},
{de:"schmecken",ph:"SHMEK-en",en:"to taste",s:"Das schmeckt wirklich lecker.",t:"That really tastes delicious."},
{de:"denken",ph:"DENK-en",en:"to think",s:"Ich denke, du hast Recht.",t:"I think you are right."},
{de:"glauben",ph:"GLOW-ben",en:"to believe",s:"Ich glaube, es regnet heute.",t:"I believe it will rain today."},
{de:"wissen",ph:"VIS-en",en:"to know (fact)",s:"Ich muss das wissen.",t:"I need to know that."},
{de:"kennen",ph:"KEN-en",en:"to know (person/place)",s:"Ich will ihn besser kennen.",t:"I want to know him better."},
{de:"verstehen",ph:"fehr-SHTAY-en",en:"to understand",s:"Ich versuche zu verstehen.",t:"I am trying to understand."},
{de:"erinnern",ph:"ehr-IN-ern",en:"to remember",s:"Kannst du dich erinnern?",t:"Can you remember?"},
{de:"vergessen",ph:"fehr-GES-en",en:"to forget",s:"Ich darf das nicht vergessen.",t:"I must not forget that."},
{de:"lernen",ph:"LEHR-nen",en:"to learn",s:"Ich will jeden Tag lernen.",t:"I want to learn every day."},
{de:"zeigen",ph:"TSY-gen",en:"to show / point",s:"Kannst du mir den Weg zeigen?",t:"Can you show me the way?"},
{de:"erklären",ph:"ehr-KLEH-ren",en:"to explain",s:"Kannst du das bitte erklären?",t:"Can you please explain that?"},
{de:"helfen",ph:"HEL-fen",en:"to help",s:"Ich will dir helfen.",t:"I want to help you."},
{de:"brauchen",ph:"BROW-khen",en:"to need",s:"Ich brauche deine Hilfe.",t:"I need your help."},
{de:"versuchen",ph:"fehr-ZOO-khen",en:"to try / attempt",s:"Ich will es versuchen.",t:"I will try it."},
{de:"schaffen",ph:"SHAHF-en",en:"to manage / achieve",s:"Ich werde das schaffen!",t:"I will manage that!"},
{de:"passieren",ph:"pah-SEER-en",en:"to happen",s:"Was wird passieren?",t:"What will happen?"},
{de:"bedeuten",ph:"beh-DOY-ten",en:"to mean",s:"Was kann das bedeuten?",t:"What can that mean?"},
{de:"kosten",ph:"KOS-ten",en:"to cost",s:"Wie viel wird das kosten?",t:"How much will that cost?"},
{de:"dauern",ph:"DOW-ern",en:"to take (time) / last",s:"Wie lange wird das dauern?",t:"How long will that take?"},
{de:"gefallen",ph:"geh-FAHL-en",en:"to please / to like sth",s:"Das wird mir sicher gefallen.",t:"I am sure I will like that."},
{de:"besuchen",ph:"beh-ZOO-khen",en:"to visit",s:"Ich will meine Großmutter besuchen.",t:"I want to visit my grandmother."},
{de:"treffen",ph:"TREF-en",en:"to meet",s:"Wir wollen uns morgen treffen.",t:"We want to meet tomorrow."},
{de:"verlassen",ph:"fehr-LAHS-en",en:"to leave",s:"Er muss das Haus verlassen.",t:"He has to leave the house."},
{de:"ankommen",ph:"AHN-kom-en",en:"to arrive",s:"Wann wirst du ankommen?",t:"When will you arrive?"},
{de:"abfahren",ph:"AHP-fah-ren",en:"to depart",s:"Der Zug wird um 10 abfahren.",t:"The train will depart at 10."},
{de:"zurückkommen",ph:"tsoo-ROOK-kom-en",en:"to come back",s:"Ich werde morgen zurückkommen.",t:"I will come back tomorrow."},
{de:"kaufen",ph:"KOW-fen",en:"to buy",s:"Ich muss Brot kaufen.",t:"I need to buy bread."},
{de:"verkaufen",ph:"fehr-KOW-fen",en:"to sell",s:"Er will sein Auto verkaufen.",t:"He wants to sell his car."},
{de:"bezahlen",ph:"beh-TSAH-len",en:"to pay",s:"Ich möchte mit Karte bezahlen.",t:"I would like to pay by card."},
{de:"bestellen",ph:"beh-SHTEL-en",en:"to order",s:"Ich will eine Pizza bestellen.",t:"I want to order a pizza."},
{de:"reservieren",ph:"reh-zehr-VEER-en",en:"to reserve / book",s:"Ich muss einen Tisch reservieren.",t:"I need to reserve a table."},
{de:"mieten",ph:"MEE-ten",en:"to rent",s:"Ich will ein Auto mieten.",t:"I want to rent a car."},
{de:"hoffen",ph:"HOF-en",en:"to hope",s:"Ich hoffe, es klappt.",t:"I hope it works out."},
{de:"wünschen",ph:"VUEN-shen",en:"to wish",s:"Ich wünsche dir alles Gute.",t:"I wish you all the best."},
{de:"lieben",ph:"LEE-ben",en:"to love",s:"Ich liebe dich sehr.",t:"I love you very much."},
{de:"hassen",ph:"HAHS-en",en:"to hate",s:"Ich hasse Lärm.",t:"I hate noise."},
{de:"spielen",ph:"SHPEE-len",en:"to play",s:"Ich will Fußball spielen.",t:"I want to play football."},
{de:"schlafen",ph:"SHLAH-fen",en:"to sleep",s:"Ich muss mehr schlafen.",t:"I need to sleep more."},
{de:"arbeiten",ph:"AR-by-ten",en:"to work",s:"Ich muss hart arbeiten.",t:"I have to work hard."},
{de:"machen",ph:"MAH-khen",en:"to make / to do",s:"Was willst du heute machen?",t:"What do you want to do today?"},
{de:"sprechen",ph:"SHPREKH-en",en:"to speak",s:"Kannst du Deutsch sprechen?",t:"Can you speak German?"},
{de:"sagen",ph:"ZAH-gen",en:"to say",s:"Was willst du sagen?",t:"What do you want to say?"},
{de:"fragen",ph:"FRAH-gen",en:"to ask",s:"Ich will dich etwas fragen.",t:"I want to ask you something."},
{de:"antworten",ph:"ANT-vor-ten",en:"to answer",s:"Du musst auf die Frage antworten.",t:"You must answer the question."},
{de:"lachen",ph:"LAHKH-en",en:"to laugh",s:"Es ist schön zu lachen.",t:"It is nice to laugh."},
{de:"weinen",ph:"VY-nen",en:"to cry",s:"Kinder können weinen.",t:"Children can cry."},
{de:"essen",ph:"ES-en",en:"to eat",s:"Ich will Pizza essen.",t:"I want to eat pizza."},
{de:"trinken",ph:"TRINK-en",en:"to drink",s:"Ich will Wasser trinken.",t:"I want to drink water."},
{de:"kochen",ph:"KOH-khen",en:"to cook",s:"Ich will heute kochen.",t:"I want to cook today."},
{de:"lesen",ph:"LAY-zen",en:"to read",s:"Ich mag Bücher lesen.",t:"I like to read books."},
{de:"schreiben",ph:"SHRY-ben",en:"to write",s:"Ich muss einen Brief schreiben.",t:"I need to write a letter."},
{de:"tanzen",ph:"TANT-sen",en:"to dance",s:"Ich will tanzen gehen.",t:"I want to go dancing."},
{de:"singen",ph:"ZING-en",en:"to sing",s:"Ich singe gern unter der Dusche.",t:"I like singing in the shower."},
{de:"fahren",ph:"FAH-ren",en:"to drive / ride",s:"Ich lerne Auto fahren.",t:"I am learning to drive."},
{de:"reisen",ph:"RY-zen",en:"to travel",s:"Ich will die Welt bereisen.",t:"I want to travel the world."},
{de:"wohnen",ph:"VOH-nen",en:"to live / reside",s:"Wo willst du wohnen?",t:"Where do you want to live?"}
],

"G3 — Daily Life Verbs":[
{de:"erzählen",ph:"ehr-TSAY-len",en:"to tell / narrate",s:"Kannst du mir eine Geschichte erzählen?",t:"Can you tell me a story?"},
{de:"berichten",ph:"beh-RISH-ten",en:"to report",s:"Er muss dem Chef berichten.",t:"He has to report to the boss."},
{de:"beschreiben",ph:"beh-SHRY-ben",en:"to describe",s:"Kannst du ihn beschreiben?",t:"Can you describe him?"},
{de:"diskutieren",ph:"dis-koo-TEER-en",en:"to discuss",s:"Wir müssen das diskutieren.",t:"We need to discuss that."},
{de:"reden",ph:"RAY-den",en:"to talk / chat",s:"Wir können reden.",t:"We can talk."},
{de:"flüstern",ph:"FLUES-tern",en:"to whisper",s:"Bitte nicht flüstern.",t:"Please do not whisper."},
{de:"schreien",ph:"SHRY-en",en:"to shout / scream",s:"Du musst nicht schreien.",t:"You do not have to shout."},
{de:"lächeln",ph:"LEKH-eln",en:"to smile",s:"Es ist schön zu lächeln.",t:"It is nice to smile."},
{de:"tippen",ph:"TIP-en",en:"to type",s:"Ich muss schnell tippen.",t:"I need to type quickly."},
{de:"zeichnen",ph:"TSYKH-nen",en:"to draw",s:"Ich lerne zeichnen.",t:"I am learning to draw."},
{de:"malen",ph:"MAH-len",en:"to paint",s:"Kinder lieben malen.",t:"Children love painting."},
{de:"drucken",ph:"DRUK-en",en:"to print",s:"Ich muss das Formular drucken.",t:"I need to print the form."},
{de:"fotografieren",ph:"fo-to-gra-FEER-en",en:"to photograph",s:"Ich will die Stadt fotografieren.",t:"I want to photograph the city."},
{de:"filmen",ph:"FIL-men",en:"to film / record video",s:"Er will das Konzert filmen.",t:"He wants to film the concert."},
{de:"anrufen",ph:"AHN-roo-fen",en:"to call (phone)",s:"Ich muss dich anrufen.",t:"I need to call you."},
{de:"herunterladen",ph:"heh-ROON-ter-lah-den",en:"to download",s:"Ich will die App herunterladen.",t:"I want to download the app."},
{de:"hochladen",ph:"HOHKH-lah-den",en:"to upload",s:"Ich muss die Datei hochladen.",t:"I need to upload the file."},
{de:"googeln",ph:"GOO-geln",en:"to google / search online",s:"Ich muss das googeln.",t:"I need to google that."},
{de:"streamen",ph:"STREE-men",en:"to stream",s:"Ich will Musik streamen.",t:"I want to stream music."},
{de:"posten",ph:"POS-ten",en:"to post (online)",s:"Sie will ein Foto posten.",t:"She wants to post a photo."},
{de:"waschen",ph:"VAH-shen",en:"to wash",s:"Ich muss die Wäsche waschen.",t:"I need to wash the laundry."},
{de:"putzen",ph:"POOT-sen",en:"to clean",s:"Ich muss das Zimmer putzen.",t:"I need to clean the room."},
{de:"aufräumen",ph:"OWF-roy-men",en:"to tidy up",s:"Bitte dein Zimmer aufräumen.",t:"Please tidy up your room."},
{de:"bügeln",ph:"BUE-geln",en:"to iron",s:"Ich muss das Hemd bügeln.",t:"I need to iron the shirt."},
{de:"reparieren",ph:"reh-pah-REER-en",en:"to repair",s:"Kann er das Auto reparieren?",t:"Can he repair the car?"},
{de:"bauen",ph:"BOW-en",en:"to build",s:"Sie wollen ein Haus bauen.",t:"They want to build a house."},
{de:"messen",ph:"MES-en",en:"to measure",s:"Ich muss die Wand messen.",t:"I need to measure the wall."},
{de:"aufstehen",ph:"OWF-shtay-en",en:"to get up",s:"Ich muss früh aufstehen.",t:"I have to get up early."},
{de:"anziehen",ph:"AHN-tsee-en",en:"to put on (clothes)",s:"Ich muss mich warm anziehen.",t:"I need to dress warmly."},
{de:"ausziehen",ph:"OWS-tsee-en",en:"to take off (clothes)",s:"Bitte die Schuhe ausziehen.",t:"Please take off your shoes."},
{de:"duschen",ph:"DOO-shen",en:"to shower",s:"Ich muss noch duschen.",t:"I still need to shower."},
{de:"schminken",ph:"SHMINK-en",en:"to put on makeup",s:"Sie will sich schminken.",t:"She wants to put on makeup."},
{de:"einschlafen",ph:"INE-shlah-fen",en:"to fall asleep",s:"Ich kann nicht einschlafen.",t:"I cannot fall asleep."},
{de:"aufwachen",ph:"OWF-vah-khen",en:"to wake up",s:"Ich muss früh aufwachen.",t:"I need to wake up early."},
{de:"studieren",ph:"shtoo-DEER-en",en:"to study (university)",s:"Er will in München studieren.",t:"He wants to study in Munich."},
{de:"unterrichten",ph:"oon-ter-RISH-ten",en:"to teach",s:"Sie will Kinder unterrichten.",t:"She wants to teach children."},
{de:"üben",ph:"UE-ben",en:"to practise",s:"Ich muss Deutsch üben.",t:"I need to practise German."},
{de:"prüfen",ph:"PRUE-fen",en:"to check / to test",s:"Er muss die Zahlen prüfen.",t:"He needs to check the numbers."},
{de:"übersetzen",ph:"ue-ber-ZET-sen",en:"to translate",s:"Kannst du das übersetzen?",t:"Can you translate that?"},
{de:"wiederholen",ph:"vee-der-HOH-len",en:"to repeat",s:"Bitte das Wort wiederholen.",t:"Please repeat the word."},
{de:"verbessern",ph:"fehr-BES-ern",en:"to improve",s:"Ich will mein Deutsch verbessern.",t:"I want to improve my German."},
{de:"vorbereiten",ph:"for-beh-RY-ten",en:"to prepare",s:"Ich muss mich vorbereiten.",t:"I need to prepare myself."},
{de:"organisieren",ph:"or-gah-nee-ZEER-en",en:"to organise",s:"Wer kann das organisieren?",t:"Who can organise that?"},
{de:"planen",ph:"PLAH-nen",en:"to plan",s:"Wir müssen die Reise planen.",t:"We need to plan the trip."},
{de:"ändern",ph:"END-ern",en:"to change / alter",s:"Ich will meinen Plan ändern.",t:"I want to change my plan."},
{de:"trainieren",ph:"tray-NEER-en",en:"to train / work out",s:"Ich will jeden Tag trainieren.",t:"I want to train every day."},
{de:"schwimmen",ph:"SHVIM-en",en:"to swim",s:"Kannst du gut schwimmen?",t:"Can you swim well?"},
{de:"wandern",ph:"VAHN-dern",en:"to hike",s:"Wir wollen am Wochenende wandern.",t:"We want to hike at the weekend."},
{de:"radfahren",ph:"RAHT-fah-ren",en:"to cycle",s:"Ich will jeden Tag radfahren.",t:"I want to cycle every day."},
{de:"feiern",ph:"FY-ern",en:"to celebrate",s:"Wir wollen deinen Geburtstag feiern.",t:"We want to celebrate your birthday."},
{de:"einladen",ph:"INE-lah-den",en:"to invite",s:"Ich will alle einladen.",t:"I want to invite everyone."},
{de:"empfehlen",ph:"emp-FAY-len",en:"to recommend",s:"Kannst du ein Restaurant empfehlen?",t:"Can you recommend a restaurant?"},
{de:"warnen",ph:"VAHR-nen",en:"to warn",s:"Ich muss ihn warnen.",t:"I need to warn him."},
{de:"versprechen",ph:"fehr-SHPREKH-en",en:"to promise",s:"Ich werde es versprechen.",t:"I will promise it."},
{de:"erlauben",ph:"ehr-LOW-ben",en:"to allow / permit",s:"Darfst du das erlauben?",t:"Are you allowed to permit that?"},
{de:"verbieten",ph:"fehr-BEE-ten",en:"to forbid / ban",s:"Man darf das hier verbieten.",t:"They can forbid that here."},
{de:"kontrollieren",ph:"kon-tro-LEER-en",en:"to check / control",s:"Er muss die Karte kontrollieren.",t:"He has to check the card."},
{de:"wählen",ph:"VAY-len",en:"to choose / elect",s:"Du kannst frei wählen.",t:"You can choose freely."},
{de:"entscheiden",ph:"ent-SHY-den",en:"to decide",s:"Ich muss jetzt entscheiden.",t:"I have to decide now."},
{de:"sich freuen",ph:"ZISH FROY-en",en:"to be happy / look forward",s:"Ich freue mich auf den Urlaub.",t:"I am looking forward to the holiday."},
{de:"sich ärgern",ph:"ZISH EHR-gern",en:"to be annoyed",s:"Ich ärgere mich darüber.",t:"I am annoyed about that."},
{de:"sich beeilen",ph:"ZISH beh-EYE-len",en:"to hurry",s:"Du musst dich beeilen.",t:"You need to hurry."},
{de:"sich erholen",ph:"ZISH ehr-HOH-len",en:"to recover / relax",s:"Ich muss mich erholen.",t:"I need to recover."},
{de:"sich vorstellen",ph:"ZISH FOR-shtel-en",en:"to introduce oneself",s:"Ich möchte mich vorstellen.",t:"I would like to introduce myself."},
{de:"sich irren",ph:"ZISH IR-en",en:"to be wrong / mistaken",s:"Ich könnte mich irren.",t:"I could be mistaken."},
{de:"sich kümmern",ph:"ZISH KOOM-ern",en:"to take care of",s:"Er will sich kümmern.",t:"He wants to take care of it."},
{de:"sich befinden",ph:"ZISH beh-FIN-den",en:"to be located / feel",s:"Wie befindest du dich?",t:"How are you feeling?"},
{de:"backen",ph:"BAH-ken",en:"to bake",s:"Ich will einen Kuchen backen.",t:"I want to bake a cake."},
{de:"schneiden",ph:"SHNY-den",en:"to cut",s:"Ich muss das Brot schneiden.",t:"I need to cut the bread."},
{de:"mischen",ph:"MISH-en",en:"to mix",s:"Bitte die Zutaten mischen.",t:"Please mix the ingredients."},
{de:"braten",ph:"BRAH-ten",en:"to fry / roast",s:"Ich will Fleisch braten.",t:"I want to fry meat."},
{de:"würzen",ph:"VUER-tsen",en:"to season / spice",s:"Du musst die Suppe würzen.",t:"You need to season the soup."},
{de:"servieren",ph:"zehr-VEER-en",en:"to serve",s:"Wann wird das Essen servieren?",t:"When will the food be served?"},
{de:"abkühlen",ph:"AHP-kue-len",en:"to cool down",s:"Lass das Essen abkühlen.",t:"Let the food cool down."},
{de:"zubereiten",ph:"TSOO-beh-ry-ten",en:"to prepare (food)",s:"Ich will das Essen zubereiten.",t:"I want to prepare the food."},
{de:"einkaufen",ph:"INE-kow-fen",en:"to go shopping",s:"Ich muss einkaufen gehen.",t:"I need to go shopping."},
{de:"abholen",ph:"AHP-hoh-len",en:"to pick up (person/thing)",s:"Kannst du mich abholen?",t:"Can you pick me up?"},
{de:"hinzufügen",ph:"HIN-tsoo-fyoo-gen",en:"to add",s:"Ich will Zucker hinzufügen.",t:"I want to add sugar."},
{de:"erhalten",ph:"ehr-HAHL-ten",en:"to receive / get",s:"Ich werde eine Antwort erhalten.",t:"I will receive an answer."},
{de:"schicken",ph:"SHIK-en",en:"to send",s:"Ich muss die E-Mail schicken.",t:"I need to send the email."},
{de:"teilen",ph:"TY-len",en:"to share / divide",s:"Lass uns das teilen.",t:"Let us share that."},
{de:"zeigen",ph:"TSY-gen",en:"to show",s:"Kannst du mir das zeigen?",t:"Can you show me that?"},
{de:"mitnehmen",ph:"MIT-nay-men",en:"to take along",s:"Kann ich dich mitnehmen?",t:"Can I take you along?"},
{de:"aufpassen",ph:"OWF-pah-sen",en:"to watch out / take care",s:"Bitte aufpassen!",t:"Please watch out!"},
{de:"nachdenken",ph:"NAHKH-denk-en",en:"to think about / reflect",s:"Ich muss darüber nachdenken.",t:"I need to think about it."},
{de:"zweifeln",ph:"TSVY-feln",en:"to doubt",s:"Ich fange an zu zweifeln.",t:"I am starting to doubt."},
{de:"träumen",ph:"TROY-men",en:"to dream",s:"Ich träume von einer Reise.",t:"I dream of a trip."},
{de:"zuhören",ph:"TSOO-huh-ren",en:"to listen attentively",s:"Bitte mir zuhören.",t:"Please listen to me."},
{de:"vorlesen",ph:"FOR-lay-zen",en:"to read aloud",s:"Kannst du das vorlesen?",t:"Can you read that aloud?"},
{de:"aufschreiben",ph:"OWF-shry-ben",en:"to write down",s:"Ich muss das aufschreiben.",t:"I need to write that down."},
{de:"unterschreiben",ph:"oon-ter-SHRY-ben",en:"to sign",s:"Bitte hier unterschreiben.",t:"Please sign here."},
{de:"vergeben",ph:"fehr-GAY-ben",en:"to forgive",s:"Ich kann vergeben.",t:"I can forgive."},
{de:"kämpfen",ph:"KEMF-en",en:"to fight",s:"Er muss für seine Rechte kämpfen.",t:"He must fight for his rights."},
{de:"gelingen",ph:"geh-LING-en",en:"to succeed",s:"Es wird mir gelingen.",t:"I will succeed."},
{de:"fehlen",ph:"FAY-len",en:"to be missing / to miss",s:"Du wirst mir fehlen.",t:"I will miss you."}
],

"G4 — People & Body":[
{de:"Mutter",ph:"MOOT-ter (die)",en:"mother",s:"Meine Mutter kocht sehr gut.",t:"My mother cooks very well."},
{de:"Vater",ph:"FAH-ter (der)",en:"father",s:"Mein Vater arbeitet in Berlin.",t:"My father works in Berlin."},
{de:"Eltern",ph:"EL-tern (die)",en:"parents",s:"Meine Eltern wohnen in Hamburg.",t:"My parents live in Hamburg."},
{de:"Bruder",ph:"BROO-der (der)",en:"brother",s:"Mein Bruder ist zwei Jahre älter.",t:"My brother is two years older."},
{de:"Schwester",ph:"SHVES-ter (die)",en:"sister",s:"Meine Schwester studiert Medizin.",t:"My sister is studying medicine."},
{de:"Sohn",ph:"ZOHN (der)",en:"son",s:"Ihr Sohn ist sehr klug.",t:"Her son is very clever."},
{de:"Tochter",ph:"TOKH-ter (die)",en:"daughter",s:"Ihre Tochter lernt Klavier.",t:"Her daughter is learning piano."},
{de:"Großmutter",ph:"GROHS-moo-ter (die)",en:"grandmother",s:"Meine Großmutter macht gute Kuchen.",t:"My grandmother makes good cakes."},
{de:"Großvater",ph:"GROHS-fah-ter (der)",en:"grandfather",s:"Mein Großvater ist achtzig Jahre alt.",t:"My grandfather is eighty years old."},
{de:"Enkel",ph:"ENK-el (der)",en:"grandson / grandchild",s:"Der Enkel besucht die Großeltern.",t:"The grandchild visits the grandparents."},
{de:"Tante",ph:"TAHN-teh (die)",en:"aunt",s:"Meine Tante wohnt in München.",t:"My aunt lives in Munich."},
{de:"Onkel",ph:"ONK-el (der)",en:"uncle",s:"Mein Onkel hat ein Restaurant.",t:"My uncle has a restaurant."},
{de:"Cousin",ph:"koo-ZAN (der)",en:"male cousin",s:"Mein Cousin spielt Gitarre.",t:"My cousin plays guitar."},
{de:"Cousine",ph:"koo-ZEE-neh (die)",en:"female cousin",s:"Meine Cousine wohnt in Köln.",t:"My female cousin lives in Cologne."},
{de:"Geschwister",ph:"geh-SHVIS-ter (die)",en:"siblings",s:"Ich habe drei Geschwister.",t:"I have three siblings."},
{de:"Familie",ph:"fah-MEE-lee-eh (die)",en:"family",s:"Meine Familie ist sehr groß.",t:"My family is very big."},
{de:"Kind",ph:"KINT (das)",en:"child",s:"Das Kind spielt im Garten.",t:"The child is playing in the garden."},
{de:"Baby",ph:"BAY-bee (das)",en:"baby",s:"Das Baby schläft den ganzen Tag.",t:"The baby sleeps all day."},
{de:"Verwandte",ph:"fehr-VAHNT-eh (die)",en:"relatives",s:"Wir besuchen unsere Verwandte.",t:"We are visiting our relatives."},
{de:"Ehemann",ph:"EH-eh-mahn (der)",en:"husband",s:"Ihr Ehemann ist Arzt.",t:"Her husband is a doctor."},
{de:"Ehefrau",ph:"EH-eh-frow (die)",en:"wife",s:"Sein Ehefrau ist sehr nett.",t:"His wife is very nice."},
{de:"Freund",ph:"FROYNT (der)",en:"friend / boyfriend",s:"Mein Freund kommt heute.",t:"My friend is coming today."},
{de:"Freundin",ph:"FROYN-din (die)",en:"friend / girlfriend",s:"Meine Freundin heißt Anna.",t:"My girlfriend is called Anna."},
{de:"Kollege",ph:"kol-LAY-geh (der)",en:"colleague",s:"Mein Kollege ist sehr hilfsbereit.",t:"My colleague is very helpful."},
{de:"Nachbar",ph:"NAHKH-bar (der)",en:"neighbour",s:"Mein Nachbar hat einen Hund.",t:"My neighbour has a dog."},
{de:"Mensch",ph:"MENSH (der)",en:"person / human being",s:"Jeder Mensch ist wichtig.",t:"Every person is important."},
{de:"Mann",ph:"MAHN (der)",en:"man",s:"Der Mann hilft ihr.",t:"The man helps her."},
{de:"Frau",ph:"FROW (die)",en:"woman / Mrs",s:"Die Frau spricht sehr gut Deutsch.",t:"The woman speaks German very well."},
{de:"Junge",ph:"YOONG-eh (der)",en:"boy",s:"Der Junge spielt Fußball.",t:"The boy is playing football."},
{de:"Mädchen",ph:"MAYT-shen (das)",en:"girl",s:"Das Mädchen lacht.",t:"The girl is laughing."},
{de:"Lehrer",ph:"LAY-rer (der)",en:"teacher (male)",s:"Der Lehrer erklärt die Aufgabe.",t:"The teacher explains the task."},
{de:"Arzt",ph:"ARTST (der)",en:"doctor (male)",s:"Der Arzt verschreibt ein Medikament.",t:"The doctor prescribes a medicine."},
{de:"Krankenschwester",ph:"KRAHN-ken-shves-ter (die)",en:"nurse",s:"Die Krankenschwester ist sehr nett.",t:"The nurse is very nice."},
{de:"Ingenieur",ph:"in-zheh-nee-EUR (der)",en:"engineer",s:"Er ist Ingenieur bei BMW.",t:"He is an engineer at BMW."},
{de:"Koch",ph:"KOKH (der)",en:"cook / chef",s:"Der Koch macht eine Suppe.",t:"The chef is making a soup."},
{de:"Kellner",ph:"KEL-ner (der)",en:"waiter",s:"Der Kellner bringt die Speisekarte.",t:"The waiter brings the menu."},
{de:"Polizist",ph:"po-li-TSIST (der)",en:"police officer",s:"Der Polizist hilft dem alten Mann.",t:"The police officer helps the old man."},
{de:"Feuerwehrmann",ph:"FOY-er-vehr-mahn (der)",en:"firefighter",s:"Der Feuerwehrmann ist mutig.",t:"The firefighter is brave."},
{de:"Journalist",ph:"zhoor-nah-LIST (der)",en:"journalist",s:"Der Journalist schreibt einen Artikel.",t:"The journalist writes an article."},
{de:"Wissenschaftler",ph:"VIS-en-shahft-ler (der)",en:"scientist",s:"Der Wissenschaftler forscht.",t:"The scientist is doing research."},
{de:"Name",ph:"NAH-meh (der)",en:"name",s:"Wie ist dein Name?",t:"What is your name?"},
{de:"Vorname",ph:"FOR-nah-meh (der)",en:"first name",s:"Mein Vorname ist Ali.",t:"My first name is Ali."},
{de:"Nachname",ph:"NAHKH-nah-meh (der)",en:"surname",s:"Wie ist dein Nachname?",t:"What is your surname?"},
{de:"Alter",ph:"AHL-ter (das)",en:"age",s:"Was ist dein Alter?",t:"What is your age?"},
{de:"Geburtstag",ph:"geh-BOORTSZ-tahg (der)",en:"birthday",s:"Wann ist dein Geburtstag?",t:"When is your birthday?"},
{de:"Nationalität",ph:"nah-tsyo-nah-li-TEHT (die)",en:"nationality",s:"Was ist deine Nationalität?",t:"What is your nationality?"},
{de:"Beruf",ph:"beh-ROOF (der)",en:"profession / job",s:"Was ist dein Beruf?",t:"What is your profession?"},
{de:"Kopf",ph:"KOPF (der)",en:"head",s:"Mir tut der Kopf weh.",t:"My head hurts."},
{de:"Gesicht",ph:"geh-ZISHT (das)",en:"face",s:"Sie hat ein freundliches Gesicht.",t:"She has a friendly face."},
{de:"Auge",ph:"OW-geh (das)",en:"eye",s:"Er hat blaue Augen.",t:"He has blue eyes."},
{de:"Ohr",ph:"OHR (das)",en:"ear",s:"Das Ohr tut mir weh.",t:"My ear hurts."},
{de:"Nase",ph:"NAH-zeh (die)",en:"nose",s:"Er hat eine große Nase.",t:"He has a big nose."},
{de:"Mund",ph:"MOOND (der)",en:"mouth",s:"Öffne bitte den Mund.",t:"Please open your mouth."},
{de:"Zahn",ph:"TSAHN (der)",en:"tooth",s:"Mein Zahn tut weh.",t:"My tooth hurts."},
{de:"Haar",ph:"HAHR (das)",en:"hair",s:"Sie hat langes Haar.",t:"She has long hair."},
{de:"Hand",ph:"HAHNT (die)",en:"hand",s:"Gib mir deine Hand.",t:"Give me your hand."},
{de:"Finger",ph:"FING-er (der)",en:"finger",s:"Er zeigt mit dem Finger.",t:"He points with his finger."},
{de:"Fuß",ph:"FOOS (der)",en:"foot",s:"Mein Fuß tut weh.",t:"My foot hurts."},
{de:"Bein",ph:"BINE (das)",en:"leg",s:"Er hat ein verletztes Bein.",t:"He has an injured leg."},
{de:"Arm",ph:"AHRM (der)",en:"arm",s:"Sie bricht sich den Arm.",t:"She breaks her arm."},
{de:"Rücken",ph:"RUEK-en (der)",en:"back",s:"Mein Rücken schmerzt.",t:"My back hurts."},
{de:"Bauch",ph:"BOWKH (der)",en:"stomach / belly",s:"Mir tut der Bauch weh.",t:"My stomach hurts."},
{de:"Herz",ph:"HEHRTS (das)",en:"heart",s:"Das Herz schlägt schnell.",t:"The heart beats fast."},
{de:"Haut",ph:"HOWT (die)",en:"skin",s:"Er hat empfindliche Haut.",t:"He has sensitive skin."},
{de:"Blut",ph:"BLOOT (das)",en:"blood",s:"Er hat Blut an der Hand.",t:"He has blood on his hand."},
{de:"Stimme",ph:"SHTIM-eh (die)",en:"voice",s:"Sie hat eine schöne Stimme.",t:"She has a beautiful voice."},
{de:"Körper",ph:"KUH-per (der)",en:"body",s:"Ein gesunder Körper ist wichtig.",t:"A healthy body is important."},
{de:"Gesundheit",ph:"geh-ZOONT-hyte (die)",en:"health",s:"Gesundheit ist das Wichtigste.",t:"Health is the most important thing."},
{de:"Krankheit",ph:"KRAHNK-hyte (die)",en:"illness / disease",s:"Diese Krankheit ist heilbar.",t:"This illness is curable."},
{de:"Schmerz",ph:"SHMERTZ (der)",en:"pain",s:"Er hat starken Schmerz.",t:"He has strong pain."},
{de:"Fieber",ph:"FEE-ber (das)",en:"fever",s:"Das Kind hat Fieber.",t:"The child has a fever."},
{de:"Medikament",ph:"meh-di-kah-MENT (das)",en:"medicine / medication",s:"Er nimmt das Medikament täglich.",t:"He takes the medication daily."},
{de:"Apotheke",ph:"ah-po-TAY-keh (die)",en:"pharmacy",s:"Ich gehe zur Apotheke.",t:"I am going to the pharmacy."},
{de:"Krankenhaus",ph:"KRAHN-ken-hows (das)",en:"hospital",s:"Er liegt im Krankenhaus.",t:"He is in hospital."},
{de:"Arzttermin",ph:"ARTST-tehr-meen (der)",en:"doctor's appointment",s:"Ich habe morgen einen Arzttermin.",t:"I have a doctor's appointment tomorrow."},
{de:"Freundschaft",ph:"FROYNT-shahft (die)",en:"friendship",s:"Freundschaft ist sehr wichtig.",t:"Friendship is very important."},
{de:"Liebe",ph:"LEE-beh (die)",en:"love",s:"Liebe macht das Leben schöner.",t:"Love makes life more beautiful."},
{de:"Hochzeit",ph:"HOKH-tsyte (die)",en:"wedding",s:"Ihre Hochzeit war wunderschön.",t:"Their wedding was beautiful."},
{de:"Scheidung",ph:"SHY-doong (die)",en:"divorce",s:"Sie haben eine Scheidung.",t:"They are getting a divorce."},
{de:"Person",ph:"pehr-ZOHN (die)",en:"person",s:"Diese Person ist sehr nett.",t:"This person is very nice."},
{de:"Leute",ph:"LOY-teh (die)",en:"people",s:"Viele Leute kommen heute.",t:"Many people are coming today."},
{de:"Partner",ph:"PAHRT-ner (der)",en:"partner",s:"Mein Partner ist sehr geduldig.",t:"My partner is very patient."},
{de:"Bekannter",ph:"beh-KAHNT-er (der)",en:"acquaintance",s:"Er ist ein Bekannter von mir.",t:"He is an acquaintance of mine."},
{de:"Erwachsener",ph:"ehr-VAHK-seh-ner (der)",en:"adult",s:"Das ist nur für Erwachsene.",t:"That is for adults only."},
{de:"Jugendlicher",ph:"YOO-gent-li-sher (der)",en:"teenager / youth",s:"Der Jugendliche lernt fleißig.",t:"The teenager studies diligently."},
{de:"Rentner",ph:"RENT-ner (der)",en:"retiree / pensioner",s:"Der Rentner geht täglich spazieren.",t:"The pensioner goes for a walk daily."},
{de:"Politiker",ph:"po-li-TIK-er (der)",en:"politician",s:"Der Politiker hält eine Rede.",t:"The politician gives a speech."},
{de:"Schauspieler",ph:"SHOW-shpee-ler (der)",en:"actor",s:"Der Schauspieler ist sehr bekannt.",t:"The actor is very famous."},
{de:"Musiker",ph:"moo-ZIK-er (der)",en:"musician",s:"Der Musiker spielt Geige.",t:"The musician plays violin."},
{de:"Sportler",ph:"SHPORT-ler (der)",en:"athlete / sportsperson",s:"Der Sportler trainiert jeden Tag.",t:"The athlete trains every day."},
{de:"Bauer",ph:"BOW-er (der)",en:"farmer",s:"Der Bauer erntet das Getreide.",t:"The farmer harvests the grain."},
{de:"Fahrer",ph:"FAH-rer (der)",en:"driver",s:"Der Fahrer kennt die Stadt gut.",t:"The driver knows the city well."}
],

"G5 — Places & Environment":[
{de:"Stadt",ph:"SHTAHT (die)",en:"city / town",s:"Die Stadt ist sehr belebt.",t:"The city is very lively."},
{de:"Dorf",ph:"DORF (das)",en:"village",s:"Das Dorf ist sehr ruhig.",t:"The village is very quiet."},
{de:"Land",ph:"LAHNT (das)",en:"country / countryside",s:"Ich lebe gern auf dem Land.",t:"I like living in the countryside."},
{de:"Hauptstadt",ph:"HOWPT-shtaht (die)",en:"capital city",s:"Berlin ist die Hauptstadt Deutschlands.",t:"Berlin is the capital city of Germany."},
{de:"Region",ph:"reh-gee-OHN (die)",en:"region",s:"Diese Region ist sehr schön.",t:"This region is very beautiful."},
{de:"Staat",ph:"SHTAHT (der)",en:"state / nation",s:"Der Staat hilft den Bürgern.",t:"The state helps the citizens."},
{de:"Welt",ph:"VELT (die)",en:"world",s:"Die Welt ist riesig.",t:"The world is huge."},
{de:"Europa",ph:"oy-ROH-pah",en:"Europe",s:"Europa hat viele Kulturen.",t:"Europe has many cultures."},
{de:"Deutschland",ph:"DOYTSH-lahnt",en:"Germany",s:"Deutschland ist sehr schön.",t:"Germany is very beautiful."},
{de:"Norden",ph:"NOR-den (der)",en:"north",s:"Er kommt aus dem Norden.",t:"He comes from the north."},
{de:"Süden",ph:"ZUE-den (der)",en:"south",s:"Es ist warm im Süden.",t:"It is warm in the south."},
{de:"Osten",ph:"OS-ten (der)",en:"east",s:"Die Sonne geht im Osten auf.",t:"The sun rises in the east."},
{de:"Westen",ph:"VES-ten (der)",en:"west",s:"Die Sonne geht im Westen unter.",t:"The sun sets in the west."},
{de:"Berg",ph:"BEHRG (der)",en:"mountain",s:"Der Berg ist sehr hoch.",t:"The mountain is very high."},
{de:"Tal",ph:"TAHL (das)",en:"valley",s:"Das Dorf liegt im Tal.",t:"The village is in the valley."},
{de:"Fluss",ph:"FLOOS (der)",en:"river",s:"Der Fluss ist breit und tief.",t:"The river is wide and deep."},
{de:"See",ph:"ZAY (der)",en:"lake",s:"Wir schwimmen im See.",t:"We swim in the lake."},
{de:"Meer",ph:"MEHR (das)",en:"sea",s:"Das Meer ist sehr ruhig.",t:"The sea is very calm."},
{de:"Strand",ph:"SHTRAHNT (der)",en:"beach",s:"Wir liegen am Strand.",t:"We are lying on the beach."},
{de:"Wald",ph:"VAHLT (der)",en:"forest",s:"Im Wald gibt es viele Tiere.",t:"There are many animals in the forest."},
{de:"Feld",ph:"FELT (das)",en:"field",s:"Das Feld ist voller Blumen.",t:"The field is full of flowers."},
{de:"Wiese",ph:"VEE-zeh (die)",en:"meadow",s:"Die Kühe stehen auf der Wiese.",t:"The cows stand in the meadow."},
{de:"Wüste",ph:"VUES-teh (die)",en:"desert",s:"Die Sahara ist eine Wüste.",t:"The Sahara is a desert."},
{de:"Insel",ph:"IN-zel (die)",en:"island",s:"Die Insel ist wunderschön.",t:"The island is wonderful."},
{de:"Küste",ph:"KUES-teh (die)",en:"coast",s:"Wir wohnen an der Küste.",t:"We live on the coast."},
{de:"Park",ph:"PAHRK (der)",en:"park",s:"Die Kinder spielen im Park.",t:"The children play in the park."},
{de:"Garten",ph:"GAHR-ten (der)",en:"garden",s:"Er hat einen schönen Garten.",t:"He has a beautiful garden."},
{de:"Haus",ph:"HOWS (das)",en:"house",s:"Das Haus hat drei Etagen.",t:"The house has three floors."},
{de:"Wohnung",ph:"VOH-noong (die)",en:"flat / apartment",s:"Ich suche eine neue Wohnung.",t:"I am looking for a new flat."},
{de:"Zimmer",ph:"TSIM-er (das)",en:"room",s:"Das Zimmer ist zu klein.",t:"The room is too small."},
{de:"Küche",ph:"KUE-sheh (die)",en:"kitchen",s:"Die Küche ist sehr modern.",t:"The kitchen is very modern."},
{de:"Badezimmer",ph:"BAH-deh-tsim-er (das)",en:"bathroom",s:"Das Badezimmer ist sauber.",t:"The bathroom is clean."},
{de:"Schlafzimmer",ph:"SHLAHF-tsim-er (das)",en:"bedroom",s:"Mein Schlafzimmer ist ruhig.",t:"My bedroom is quiet."},
{de:"Wohnzimmer",ph:"VOHN-tsim-er (das)",en:"living room",s:"Wir sitzen im Wohnzimmer.",t:"We are sitting in the living room."},
{de:"Keller",ph:"KEL-er (der)",en:"basement / cellar",s:"Der Keller ist dunkel.",t:"The basement is dark."},
{de:"Dachboden",ph:"DAHKH-boh-den (der)",en:"attic",s:"Im Dachboden stehen alte Möbel.",t:"Old furniture is in the attic."},
{de:"Balkon",ph:"bahl-KON (der)",en:"balcony",s:"Ich sitze gern auf dem Balkon.",t:"I like sitting on the balcony."},
{de:"Eingang",ph:"INE-gahng (der)",en:"entrance",s:"Der Eingang ist vorne.",t:"The entrance is at the front."},
{de:"Treppe",ph:"TREP-eh (die)",en:"stairs",s:"Pass auf der Treppe auf!",t:"Watch out on the stairs!"},
{de:"Aufzug",ph:"OWF-tsoog (der)",en:"lift / elevator",s:"Der Aufzug ist kaputt.",t:"The lift is broken."},
{de:"Fenster",ph:"FENS-ter (das)",en:"window",s:"Bitte das Fenster öffnen.",t:"Please open the window."},
{de:"Tür",ph:"TUER (die)",en:"door",s:"Bitte die Tür schließen.",t:"Please close the door."},
{de:"Wand",ph:"VAHNT (die)",en:"wall",s:"Das Bild hängt an der Wand.",t:"The picture hangs on the wall."},
{de:"Straße",ph:"SHTRAH-seh (die)",en:"street / road",s:"Die Straße ist sehr belebt.",t:"The street is very busy."},
{de:"Weg",ph:"VAYK (der)",en:"path / way",s:"Der Weg ist lang.",t:"The path is long."},
{de:"Platz",ph:"PLAHTS (der)",en:"square / space",s:"Der Platz ist voll.",t:"The square is full."},
{de:"Markt",ph:"MAHRKT (der)",en:"market",s:"Der Markt hat frisches Obst.",t:"The market has fresh fruit."},
{de:"Brücke",ph:"BRUEK-eh (die)",en:"bridge",s:"Die Brücke ist sehr alt.",t:"The bridge is very old."},
{de:"Kreuzung",ph:"KROYS-oong (die)",en:"crossroads / intersection",s:"An der Kreuzung links abbiegen.",t:"Turn left at the intersection."},
{de:"Ampel",ph:"AHM-pel (die)",en:"traffic light",s:"Die Ampel ist rot.",t:"The traffic light is red."},
{de:"Bushaltestelle",ph:"BOOS-hahl-teh-shtel-eh (die)",en:"bus stop",s:"Wo ist die Bushaltestelle?",t:"Where is the bus stop?"},
{de:"Schule",ph:"SHOO-leh (die)",en:"school",s:"Die Kinder gehen zur Schule.",t:"The children go to school."},
{de:"Universität",ph:"oo-ni-vehr-zi-TEHT (die)",en:"university",s:"Er studiert an der Universität.",t:"He studies at university."},
{de:"Krankenhaus",ph:"KRAHN-ken-hows (das)",en:"hospital",s:"Das Krankenhaus ist in der Mitte.",t:"The hospital is in the centre."},
{de:"Apotheke",ph:"ah-po-TAY-keh (die)",en:"pharmacy",s:"Die Apotheke ist gleich um die Ecke.",t:"The pharmacy is just around the corner."},
{de:"Bank",ph:"BAHNK (die)",en:"bank",s:"Die Bank öffnet um neun.",t:"The bank opens at nine."},
{de:"Supermarkt",ph:"ZOO-per-mahrkt (der)",en:"supermarket",s:"Ich gehe zum Supermarkt.",t:"I am going to the supermarket."},
{de:"Restaurant",ph:"res-toh-RAHNG (das)",en:"restaurant",s:"Das Restaurant ist sehr gut.",t:"The restaurant is very good."},
{de:"Café",ph:"kah-FAY (das)",en:"café",s:"Wir treffen uns im Café.",t:"We are meeting in the café."},
{de:"Hotel",ph:"hoh-TEL (das)",en:"hotel",s:"Das Hotel hat fünf Sterne.",t:"The hotel has five stars."},
{de:"Kino",ph:"KEE-noh (das)",en:"cinema",s:"Wir gehen heute ins Kino.",t:"We are going to the cinema today."},
{de:"Theater",ph:"teh-AH-ter (das)",en:"theatre",s:"Das Theater spielt heute Abend.",t:"The theatre is performing this evening."},
{de:"Museum",ph:"moo-ZAY-oom (das)",en:"museum",s:"Das Museum ist sehr interessant.",t:"The museum is very interesting."},
{de:"Bibliothek",ph:"bib-lee-oh-TAYK (die)",en:"library",s:"Die Bibliothek hat viele Bücher.",t:"The library has many books."},
{de:"Bäckerei",ph:"bek-eh-RY (die)",en:"bakery",s:"Die Bäckerei macht gutes Brot.",t:"The bakery makes good bread."},
{de:"Büro",ph:"BUE-roh (das)",en:"office",s:"Ich arbeite im Büro.",t:"I work in the office."},
{de:"Fabrik",ph:"fah-BREEK (die)",en:"factory",s:"Die Fabrik produziert Autos.",t:"The factory produces cars."},
{de:"Bahnhof",ph:"BAHN-hof (der)",en:"train station",s:"Der Bahnhof ist in der Mitte.",t:"The train station is in the centre."},
{de:"Flughafen",ph:"FLOOK-hah-fen (der)",en:"airport",s:"Der Flughafen ist sehr groß.",t:"The airport is very large."},
{de:"Hafen",ph:"HAH-fen (der)",en:"harbour / port",s:"Der Hafen ist voller Schiffe.",t:"The harbour is full of ships."},
{de:"Tankstelle",ph:"TAHNK-shtel-eh (die)",en:"petrol station",s:"Die Tankstelle ist gleich da.",t:"The petrol station is right there."},
{de:"Rathaus",ph:"RAHT-hows (das)",en:"town hall",s:"Das Rathaus steht auf dem Marktplatz.",t:"The town hall stands on the market square."},
{de:"Kirche",ph:"KEER-sheh (die)",en:"church",s:"Die Kirche ist sehr alt.",t:"The church is very old."},
{de:"Polizei",ph:"po-li-TSY (die)",en:"police",s:"Ruf die Polizei!",t:"Call the police!"},
{de:"Feuerwehr",ph:"FOY-er-vehr (die)",en:"fire brigade",s:"Die Feuerwehr kommt schnell.",t:"The fire brigade comes quickly."},
{de:"Natur",ph:"nah-TOOR (die)",en:"nature",s:"Ich liebe die Natur.",t:"I love nature."},
{de:"Umgebung",ph:"oom-GAY-boong (die)",en:"surroundings / area",s:"Die Umgebung ist sehr schön.",t:"The surroundings are very beautiful."},
{de:"Landschaft",ph:"LAHNT-shahft (die)",en:"landscape / countryside",s:"Die Landschaft ist atemberaubend.",t:"The landscape is breathtaking."},
{de:"Himmel",ph:"HIM-el (der)",en:"sky / heaven",s:"Der Himmel ist heute blau.",t:"The sky is blue today."},
{de:"Boden",ph:"BOH-den (der)",en:"floor / ground / soil",s:"Der Boden ist rutschig.",t:"The floor is slippery."},
{de:"Luft",ph:"LOOFT (die)",en:"air",s:"Die Luft ist hier frisch.",t:"The air is fresh here."},
{de:"Wasser",ph:"VAH-ser (das)",en:"water",s:"Das Wasser ist kalt.",t:"The water is cold."},
{de:"Feuer",ph:"FOY-er (das)",en:"fire",s:"Das Feuer wärmt uns.",t:"The fire warms us."},
{de:"Licht",ph:"LISHT (das)",en:"light",s:"Das Licht ist zu grell.",t:"The light is too bright."},
{de:"Schatten",ph:"SHAHT-en (der)",en:"shadow / shade",s:"Ich sitze im Schatten.",t:"I am sitting in the shade."},
{de:"Baum",ph:"BOWM (der)",en:"tree",s:"Der Baum ist sehr hoch.",t:"The tree is very tall."},
{de:"Blume",ph:"BLOO-meh (die)",en:"flower",s:"Die Blume riecht schön.",t:"The flower smells nice."},
{de:"Tier",ph:"TEER (das)",en:"animal",s:"Das Tier ist zahm.",t:"The animal is tame."},
{de:"Hund",ph:"HOONT (der)",en:"dog",s:"Der Hund bellt laut.",t:"The dog barks loudly."},
{de:"Katze",ph:"KAHT-seh (die)",en:"cat",s:"Die Katze schläft auf dem Sofa.",t:"The cat sleeps on the sofa."},
{de:"Vogel",ph:"FOH-gel (der)",en:"bird",s:"Der Vogel singt schön.",t:"The bird sings beautifully."},
{de:"Wetter",ph:"VET-er (das)",en:"weather",s:"Das Wetter ist heute schön.",t:"The weather is nice today."},
{de:"Regen",ph:"RAY-gen (der)",en:"rain",s:"Der Regen kommt.",t:"The rain is coming."},
{de:"Schnee",ph:"SHNAY (der)",en:"snow",s:"Der Schnee ist weiß.",t:"The snow is white."},
{de:"Sonne",ph:"ZON-eh (die)",en:"sun",s:"Die Sonne scheint heute.",t:"The sun is shining today."},
{de:"Wind",ph:"VINT (der)",en:"wind",s:"Der Wind ist stark.",t:"The wind is strong."},
{de:"Temperatur",ph:"tem-peh-rah-TOOR (die)",en:"temperature",s:"Die Temperatur sinkt.",t:"The temperature is dropping."}
]

}; // end of SETS — more groups added by words2.js
