// Groups 6-10 — merged into SETS after words.js loads
Object.assign(SETS, {

"G6 — Objects & Things":[
{de:"Stift",ph:"SHTIFT (der)",en:"pen",s:"Ich brauche einen Stift.",t:"I need a pen."},
{de:"Bleistift",ph:"BLY-shtift (der)",en:"pencil",s:"Hast du einen Bleistift?",t:"Do you have a pencil?"},
{de:"Papier",ph:"pah-PEER (das)",en:"paper",s:"Ich brauche mehr Papier.",t:"I need more paper."},
{de:"Notizbuch",ph:"no-TEETS-bookh (das)",en:"notebook",s:"Ich schreibe in mein Notizbuch.",t:"I write in my notebook."},
{de:"Buch",ph:"BOOKH (das)",en:"book",s:"Das Buch ist sehr interessant.",t:"The book is very interesting."},
{de:"Zeitung",ph:"TSY-toong (die)",en:"newspaper",s:"Er liest jeden Morgen die Zeitung.",t:"He reads the newspaper every morning."},
{de:"Zeitschrift",ph:"TSYT-shrift (die)",en:"magazine",s:"Die Zeitschrift ist neu.",t:"The magazine is new."},
{de:"Brief",ph:"BREEF (der)",en:"letter",s:"Ich schreibe einen Brief.",t:"I am writing a letter."},
{de:"Paket",ph:"pah-KAYT (das)",en:"package / parcel",s:"Das Paket kommt morgen.",t:"The package is coming tomorrow."},
{de:"Ordner",ph:"ORD-ner (der)",en:"folder / binder",s:"Ich brauche einen Ordner.",t:"I need a folder."},
{de:"Computer",ph:"kom-PYOO-ter (der)",en:"computer",s:"Mein Computer ist langsam.",t:"My computer is slow."},
{de:"Laptop",ph:"LAP-top (der)",en:"laptop",s:"Ich arbeite mit dem Laptop.",t:"I work with the laptop."},
{de:"Handy",ph:"HAHN-dee (das)",en:"mobile phone",s:"Mein Handy hat keinen Akku.",t:"My phone has no battery."},
{de:"Tablet",ph:"TAH-blet (das)",en:"tablet",s:"Das Kind spielt auf dem Tablet.",t:"The child plays on the tablet."},
{de:"Fernseher",ph:"FEHRN-zay-er (der)",en:"television",s:"Der Fernseher ist kaputt.",t:"The television is broken."},
{de:"Radio",ph:"RAH-dee-oh (das)",en:"radio",s:"Ich höre Musik im Radio.",t:"I listen to music on the radio."},
{de:"Kamera",ph:"KAH-meh-rah (die)",en:"camera",s:"Ich habe meine Kamera vergessen.",t:"I forgot my camera."},
{de:"Kopfhörer",ph:"KOPF-huh-rer (der)",en:"headphones",s:"Meine Kopfhörer sind kaputt.",t:"My headphones are broken."},
{de:"Tastatur",ph:"tahs-tah-TOOR (die)",en:"keyboard",s:"Die Tastatur ist zu laut.",t:"The keyboard is too loud."},
{de:"Bildschirm",ph:"BILT-shirm (der)",en:"screen / monitor",s:"Der Bildschirm ist zu hell.",t:"The screen is too bright."},
{de:"Schlüssel",ph:"SHLUE-sel (der)",en:"key",s:"Ich habe meinen Schlüssel verloren.",t:"I have lost my key."},
{de:"Uhr",ph:"OOR (die)",en:"watch / clock",s:"Die Uhr geht vor.",t:"The clock is fast."},
{de:"Brille",ph:"BRIL-eh (die)",en:"glasses",s:"Ich brauche meine Brille.",t:"I need my glasses."},
{de:"Geldbörse",ph:"GELT-buer-zeh (die)",en:"wallet / purse",s:"Ich habe meine Geldbörse verloren.",t:"I have lost my wallet."},
{de:"Tasche",ph:"TAH-sheh (die)",en:"bag",s:"Die Tasche ist schwer.",t:"The bag is heavy."},
{de:"Rucksack",ph:"ROOK-zahk (der)",en:"backpack / rucksack",s:"Mein Rucksack ist voller Bücher.",t:"My rucksack is full of books."},
{de:"Koffer",ph:"KOF-er (der)",en:"suitcase",s:"Der Koffer ist zu schwer.",t:"The suitcase is too heavy."},
{de:"Regenschirm",ph:"RAY-gen-shirm (der)",en:"umbrella",s:"Ich brauche einen Regenschirm.",t:"I need an umbrella."},
{de:"Tisch",ph:"TISH (der)",en:"table",s:"Der Tisch ist aus Holz.",t:"The table is made of wood."},
{de:"Stuhl",ph:"SHTOOL (der)",en:"chair",s:"Der Stuhl ist unbequem.",t:"The chair is uncomfortable."},
{de:"Bett",ph:"BET (das)",en:"bed",s:"Das Bett ist sehr bequem.",t:"The bed is very comfortable."},
{de:"Sofa",ph:"ZOH-fah (das)",en:"sofa / couch",s:"Wir sitzen auf dem Sofa.",t:"We are sitting on the sofa."},
{de:"Schrank",ph:"SHRAHNK (der)",en:"cupboard / wardrobe",s:"Die Kleider hängen im Schrank.",t:"The clothes hang in the wardrobe."},
{de:"Regal",ph:"reh-GAHL (das)",en:"shelf",s:"Das Regal ist voller Bücher.",t:"The shelf is full of books."},
{de:"Lampe",ph:"LAHM-peh (die)",en:"lamp",s:"Die Lampe gibt wenig Licht.",t:"The lamp gives little light."},
{de:"Spiegel",ph:"SHPEE-gel (der)",en:"mirror",s:"Ich schaue in den Spiegel.",t:"I look in the mirror."},
{de:"Teppich",ph:"TEP-ish (der)",en:"carpet / rug",s:"Der Teppich ist neu.",t:"The carpet is new."},
{de:"Kühlschrank",ph:"KUEL-shrahnk (der)",en:"fridge",s:"Der Kühlschrank ist leer.",t:"The fridge is empty."},
{de:"Waschmaschine",ph:"VAHSH-mah-shee-neh (die)",en:"washing machine",s:"Die Waschmaschine ist voll.",t:"The washing machine is full."},
{de:"Herd",ph:"HEHRT (der)",en:"cooker / stove",s:"Der Herd ist heiß.",t:"The cooker is hot."},
{de:"Topf",ph:"TOPF (der)",en:"pot",s:"Der Topf kocht.",t:"The pot is boiling."},
{de:"Pfanne",ph:"PFAHN-eh (die)",en:"frying pan",s:"Die Pfanne ist heiß.",t:"The frying pan is hot."},
{de:"Messer",ph:"MES-er (das)",en:"knife",s:"Das Messer ist scharf.",t:"The knife is sharp."},
{de:"Gabel",ph:"GAH-bel (die)",en:"fork",s:"Die Gabel liegt auf dem Tisch.",t:"The fork is on the table."},
{de:"Löffel",ph:"LUH-fel (der)",en:"spoon",s:"Ich brauche einen Löffel.",t:"I need a spoon."},
{de:"Teller",ph:"TEL-er (der)",en:"plate",s:"Der Teller ist sauber.",t:"The plate is clean."},
{de:"Tasse",ph:"TAH-seh (die)",en:"cup",s:"Darf ich eine Tasse Tee haben?",t:"May I have a cup of tea?"},
{de:"Glas",ph:"GLAHS (das)",en:"glass",s:"Das Glas ist halb voll.",t:"The glass is half full."},
{de:"Auto",ph:"OW-toh (das)",en:"car",s:"Das Auto ist kaputt.",t:"The car is broken."},
{de:"Bus",ph:"BOOS (der)",en:"bus",s:"Der Bus kommt gleich.",t:"The bus is coming soon."},
{de:"Zug",ph:"TSOOK (der)",en:"train",s:"Der Zug hat Verspätung.",t:"The train is delayed."},
{de:"Fahrrad",ph:"FAH-raht (das)",en:"bicycle",s:"Ich fahre mit dem Fahrrad.",t:"I ride the bicycle."},
{de:"Flugzeug",ph:"FLOOK-tsoyg (das)",en:"aeroplane",s:"Das Flugzeug landet um 10.",t:"The aeroplane lands at 10."},
{de:"Taxi",ph:"TAHK-see (das)",en:"taxi",s:"Ich nehme ein Taxi.",t:"I take a taxi."},
{de:"U-Bahn",ph:"OO-bahn (die)",en:"underground / metro",s:"Die U-Bahn ist schnell.",t:"The underground is fast."},
{de:"Hemd",ph:"HEMT (das)",en:"shirt",s:"Das Hemd ist weiß.",t:"The shirt is white."},
{de:"Hose",ph:"HOH-zeh (die)",en:"trousers",s:"Die Hose ist zu eng.",t:"The trousers are too tight."},
{de:"Kleid",ph:"KLYTE (das)",en:"dress",s:"Das Kleid ist sehr schön.",t:"The dress is very beautiful."},
{de:"Jacke",ph:"YAH-keh (die)",en:"jacket",s:"Die Jacke ist warm.",t:"The jacket is warm."},
{de:"Mantel",ph:"MAHN-tel (der)",en:"coat",s:"Der Mantel ist zu teuer.",t:"The coat is too expensive."},
{de:"Schuhe",ph:"SHOO-eh (die)",en:"shoes",s:"Die Schuhe sind neu.",t:"The shoes are new."},
{de:"Socken",ph:"ZOK-en (die)",en:"socks",s:"Ich ziehe Socken an.",t:"I put on socks."},
{de:"Pullover",ph:"POO-loh-ver (der)",en:"jumper / pullover",s:"Der Pullover ist warm.",t:"The jumper is warm."},
{de:"T-Shirt",ph:"TEE-shirt (das)",en:"T-shirt",s:"Ich trage ein T-Shirt.",t:"I am wearing a T-shirt."},
{de:"Mütze",ph:"MUE-tseh (die)",en:"hat / beanie",s:"Die Mütze hält den Kopf warm.",t:"The hat keeps the head warm."},
{de:"Handschuhe",ph:"HAHNT-shoo-eh (die)",en:"gloves",s:"Die Handschuhe sind warm.",t:"The gloves are warm."},
{de:"Schal",ph:"SHAHL (der)",en:"scarf",s:"Der Schal ist aus Wolle.",t:"The scarf is made of wool."},
{de:"Geld",ph:"GELT (das)",en:"money",s:"Ich habe kein Geld.",t:"I have no money."},
{de:"Münze",ph:"MUEN-tseh (die)",en:"coin",s:"Ich habe eine alte Münze.",t:"I have an old coin."},
{de:"Kreditkarte",ph:"kreh-DEET-kahr-teh (die)",en:"credit card",s:"Ich bezahle mit der Kreditkarte.",t:"I pay with the credit card."},
{de:"Pass",ph:"PAHS (der)",en:"passport",s:"Ich brauche meinen Pass.",t:"I need my passport."},
{de:"Ausweis",ph:"OWS-vyes (der)",en:"ID card",s:"Zeig mir deinen Ausweis.",t:"Show me your ID card."},
{de:"Ticket",ph:"TIK-et (das)",en:"ticket",s:"Ich kaufe ein Ticket.",t:"I buy a ticket."},
{de:"Rechnung",ph:"REKH-noong (die)",en:"bill / invoice",s:"Kann ich die Rechnung haben?",t:"Can I have the bill?"},
{de:"Vertrag",ph:"fehr-TRAHG (der)",en:"contract",s:"Ich unterschreibe den Vertrag.",t:"I sign the contract."},
{de:"Führerschein",ph:"FUE-rer-shine (der)",en:"driving licence",s:"Hast du einen Führerschein?",t:"Do you have a driving licence?"},
{de:"Formular",ph:"for-moo-LAHR (das)",en:"form",s:"Bitte das Formular ausfüllen.",t:"Please fill in the form."},
{de:"Hammer",ph:"HAHM-er (der)",en:"hammer",s:"Ich brauche einen Hammer.",t:"I need a hammer."},
{de:"Schraubenzieher",ph:"SHROW-ben-tsee-er (der)",en:"screwdriver",s:"Hast du einen Schraubenzieher?",t:"Do you have a screwdriver?"},
{de:"Eimer",ph:"EYE-mer (der)",en:"bucket",s:"Füll den Eimer mit Wasser.",t:"Fill the bucket with water."},
{de:"Pflaster",ph:"PFLAHS-ter (das)",en:"plaster / band-aid",s:"Ich brauche ein Pflaster.",t:"I need a plaster."},
{de:"Tablette",ph:"tah-BLET-eh (die)",en:"tablet / pill",s:"Nimm die Tablette nach dem Essen.",t:"Take the pill after eating."}
],

"G7 — Numbers & Time":[
{de:"eins",ph:"INES",en:"one (1)",s:"Ich habe nur eins.",t:"I only have one."},
{de:"zwei",ph:"TSVY",en:"two (2)",s:"Ich habe zwei Bücher.",t:"I have two books."},
{de:"drei",ph:"DRY",en:"three (3)",s:"Drei Katzen schlafen.",t:"Three cats are sleeping."},
{de:"vier",ph:"FEER",en:"four (4)",s:"Ich habe vier Geschwister.",t:"I have four siblings."},
{de:"fünf",ph:"FUENF",en:"five (5)",s:"Er ist fünf Jahre alt.",t:"He is five years old."},
{de:"sechs",ph:"ZEKS",en:"six (6)",s:"Ich brauche sechs Eier.",t:"I need six eggs."},
{de:"sieben",ph:"ZEE-ben",en:"seven (7)",s:"Eine Woche hat sieben Tage.",t:"A week has seven days."},
{de:"acht",ph:"AKHT",en:"eight (8)",s:"Er arbeitet acht Stunden.",t:"He works eight hours."},
{de:"neun",ph:"NOYN",en:"nine (9)",s:"Neun Schüler sind anwesend.",t:"Nine students are present."},
{de:"zehn",ph:"TSAYN",en:"ten (10)",s:"Zehn Minuten reichen.",t:"Ten minutes are enough."},
{de:"elf",ph:"ELF",en:"eleven (11)",s:"Es ist elf Uhr.",t:"It is eleven o'clock."},
{de:"zwölf",ph:"TSVULF",en:"twelve (12)",s:"Ein Jahr hat zwölf Monate.",t:"A year has twelve months."},
{de:"dreizehn",ph:"DRY-tsayn",en:"thirteen (13)",s:"Sie ist dreizehn Jahre alt.",t:"She is thirteen years old."},
{de:"vierzehn",ph:"FEER-tsayn",en:"fourteen (14)",s:"Vierzehn Tage sind zwei Wochen.",t:"Fourteen days are two weeks."},
{de:"fünfzehn",ph:"FUENF-tsayn",en:"fifteen (15)",s:"Er wartet seit fünfzehn Minuten.",t:"He has been waiting fifteen minutes."},
{de:"sechzehn",ph:"ZEKH-tsayn",en:"sixteen (16)",s:"Mit sechzehn darf man arbeiten.",t:"At sixteen you can work."},
{de:"siebzehn",ph:"ZEEP-tsayn",en:"seventeen (17)",s:"Sie ist siebzehn Jahre alt.",t:"She is seventeen years old."},
{de:"achtzehn",ph:"AKHT-tsayn",en:"eighteen (18)",s:"Mit achtzehn ist man volljährig.",t:"At eighteen you are an adult."},
{de:"neunzehn",ph:"NOYN-tsayn",en:"nineteen (19)",s:"Neunzehn Schüler kommen.",t:"Nineteen students are coming."},
{de:"zwanzig",ph:"TSVAHN-tsig",en:"twenty (20)",s:"Er ist zwanzig Jahre alt.",t:"He is twenty years old."},
{de:"dreißig",ph:"DRY-sig",en:"thirty (30)",s:"Dreißig Minuten reichen.",t:"Thirty minutes are enough."},
{de:"vierzig",ph:"FEER-tsig",en:"forty (40)",s:"Sie ist vierzig Jahre alt.",t:"She is forty years old."},
{de:"fünfzig",ph:"FUENF-tsig",en:"fifty (50)",s:"Fünfzig Prozent ist die Hälfte.",t:"Fifty percent is half."},
{de:"sechzig",ph:"ZEKH-tsig",en:"sixty (60)",s:"Er fährt sechzig km/h.",t:"He drives sixty km/h."},
{de:"siebzig",ph:"ZEEP-tsig",en:"seventy (70)",s:"Meine Oma ist siebzig.",t:"My grandma is seventy."},
{de:"achtzig",ph:"AKHT-tsig",en:"eighty (80)",s:"Das Haus ist achtzig Jahre alt.",t:"The house is eighty years old."},
{de:"neunzig",ph:"NOYN-tsig",en:"ninety (90)",s:"Neunzig Prozent sind fast alle.",t:"Ninety percent is almost all."},
{de:"hundert",ph:"HOON-dert",en:"hundred (100)",s:"Hundert Leute waren dort.",t:"A hundred people were there."},
{de:"tausend",ph:"TOW-zent",en:"thousand (1000)",s:"Das kostet tausend Euro.",t:"That costs a thousand euros."},
{de:"Million",ph:"mil-ee-OHN (die)",en:"million",s:"Eine Million Menschen leben hier.",t:"A million people live here."},
{de:"Montag",ph:"MON-tahg (der)",en:"Monday",s:"Am Montag gehe ich zur Arbeit.",t:"On Monday I go to work."},
{de:"Dienstag",ph:"DEENS-tahg (der)",en:"Tuesday",s:"Dienstag ist mein freier Tag.",t:"Tuesday is my day off."},
{de:"Mittwoch",ph:"MIT-vokh (der)",en:"Wednesday",s:"Am Mittwoch haben wir Sport.",t:"On Wednesday we have sport."},
{de:"Donnerstag",ph:"DON-ers-tahg (der)",en:"Thursday",s:"Donnerstag ist fast Wochenende.",t:"Thursday is almost the weekend."},
{de:"Freitag",ph:"FRY-tahg (der)",en:"Friday",s:"Freitag ist mein Lieblingstag.",t:"Friday is my favourite day."},
{de:"Samstag",ph:"ZAHMS-tahg (der)",en:"Saturday",s:"Samstag schlafe ich lange.",t:"On Saturday I sleep in."},
{de:"Sonntag",ph:"ZON-tahg (der)",en:"Sunday",s:"Sonntag ist ein Ruhetag.",t:"Sunday is a day of rest."},
{de:"Januar",ph:"YAH-noo-ahr (der)",en:"January",s:"Januar ist der kälteste Monat.",t:"January is the coldest month."},
{de:"Februar",ph:"FAY-broo-ahr (der)",en:"February",s:"Februar ist der kürzeste Monat.",t:"February is the shortest month."},
{de:"März",ph:"MEHRTS (der)",en:"March",s:"Im März beginnt der Frühling.",t:"Spring begins in March."},
{de:"April",ph:"ah-PRIL (der)",en:"April",s:"April macht das Wetter bunt.",t:"April makes the weather changeable."},
{de:"Mai",ph:"MY (der)",en:"May",s:"Im Mai blühen die Blumen.",t:"Flowers bloom in May."},
{de:"Juni",ph:"YOO-nee (der)",en:"June",s:"Juni ist warm und sonnig.",t:"June is warm and sunny."},
{de:"Juli",ph:"YOO-lee (der)",en:"July",s:"Im Juli fahren wir in Urlaub.",t:"We go on holiday in July."},
{de:"August",ph:"OW-goost (der)",en:"August",s:"August ist der heißeste Monat.",t:"August is the hottest month."},
{de:"September",ph:"zep-TEM-ber (der)",en:"September",s:"Im September beginnt die Schule.",t:"School starts in September."},
{de:"Oktober",ph:"ok-TOH-ber (der)",en:"October",s:"Oktober ist bunt und kühl.",t:"October is colourful and cool."},
{de:"November",ph:"no-VEM-ber (der)",en:"November",s:"November ist oft grau und kalt.",t:"November is often grey and cold."},
{de:"Dezember",ph:"deh-TSEM-ber (der)",en:"December",s:"Im Dezember ist Weihnachten.",t:"Christmas is in December."},
{de:"Frühling",ph:"FRUEL-ing (der)",en:"spring",s:"Im Frühling wird es wärmer.",t:"It gets warmer in spring."},
{de:"Sommer",ph:"ZOM-er (der)",en:"summer",s:"Im Sommer fahren wir ans Meer.",t:"In summer we go to the sea."},
{de:"Herbst",ph:"HEHRPST (der)",en:"autumn",s:"Im Herbst fallen die Blätter.",t:"Leaves fall in autumn."},
{de:"Winter",ph:"VIN-ter (der)",en:"winter",s:"Der Winter ist kalt.",t:"Winter is cold."},
{de:"Sekunde",ph:"zeh-KOON-deh (die)",en:"second",s:"Ich komme in einer Sekunde.",t:"I am coming in a second."},
{de:"Minute",ph:"mee-NOO-teh (die)",en:"minute",s:"Ich brauche zehn Minuten.",t:"I need ten minutes."},
{de:"Stunde",ph:"SHTOON-deh (die)",en:"hour",s:"Ich warte seit einer Stunde.",t:"I have been waiting for an hour."},
{de:"Tag",ph:"TAHG (der)",en:"day",s:"Heute ist ein schöner Tag.",t:"Today is a beautiful day."},
{de:"Woche",ph:"VOH-kheh (die)",en:"week",s:"Ich komme nächste Woche.",t:"I am coming next week."},
{de:"Monat",ph:"MOH-naht (der)",en:"month",s:"Ich bin seit einem Monat hier.",t:"I have been here for a month."},
{de:"Jahr",ph:"YAHR (das)",en:"year",s:"Dieses Jahr reise ich viel.",t:"This year I am travelling a lot."},
{de:"Morgen",ph:"MOR-gen (der)",en:"morning",s:"Ich stehe jeden Morgen früh auf.",t:"I get up early every morning."},
{de:"Mittag",ph:"MIT-tahg (der)",en:"midday / noon",s:"Wir essen um Mittag.",t:"We eat at midday."},
{de:"Nachmittag",ph:"NAHKH-mit-tahg (der)",en:"afternoon",s:"Am Nachmittag mache ich Sport.",t:"In the afternoon I do sport."},
{de:"Abend",ph:"AH-bent (der)",en:"evening",s:"Am Abend lese ich ein Buch.",t:"In the evening I read a book."},
{de:"Nacht",ph:"NAKHT (die)",en:"night",s:"Die Nacht ist kalt.",t:"The night is cold."},
{de:"Mitternacht",ph:"MIT-ter-nakht (die)",en:"midnight",s:"Um Mitternacht feiern wir.",t:"We celebrate at midnight."},
{de:"übermorgen",ph:"UE-ber-mor-gen",en:"the day after tomorrow",s:"Ich reise übermorgen ab.",t:"I leave the day after tomorrow."},
{de:"vorgestern",ph:"FOR-ges-tern",en:"the day before yesterday",s:"Vorgestern war es noch warm.",t:"The day before yesterday it was still warm."},
{de:"bald",ph:"BAHLT",en:"soon",s:"Er kommt bald.",t:"He is coming soon."},
{de:"gerade",ph:"geh-RAH-deh",en:"just now / currently",s:"Ich bin gerade beschäftigt.",t:"I am busy right now."},
{de:"täglich",ph:"TAYK-lish",en:"daily",s:"Ich lerne täglich Deutsch.",t:"I learn German daily."},
{de:"wöchentlich",ph:"VUH-khent-lish",en:"weekly",s:"Wir treffen uns wöchentlich.",t:"We meet weekly."},
{de:"monatlich",ph:"MOH-naht-lish",en:"monthly",s:"Die Miete zahle ich monatlich.",t:"I pay the rent monthly."},
{de:"jährlich",ph:"YEH-rlish",en:"yearly / annual",s:"Das Festival ist jährlich.",t:"The festival is annual."},
{de:"Datum",ph:"DAH-toom (das)",en:"date",s:"Was ist das Datum heute?",t:"What is the date today?"},
{de:"Termin",ph:"tehr-MEEN (der)",en:"appointment",s:"Ich habe morgen einen Termin.",t:"I have an appointment tomorrow."},
{de:"Feiertag",ph:"FY-er-tahg (der)",en:"public holiday",s:"Morgen ist ein Feiertag.",t:"Tomorrow is a public holiday."},
{de:"Urlaub",ph:"OOR-lowp (der)",en:"holiday / vacation",s:"Ich freue mich auf den Urlaub.",t:"I am looking forward to the holiday."},
{de:"Wochenende",ph:"VOH-khen-en-deh (das)",en:"weekend",s:"Am Wochenende schlafe ich lang.",t:"At the weekend I sleep in."},
{de:"Uhrzeit",ph:"OOR-tsyte (die)",en:"time (on the clock)",s:"Was ist die Uhrzeit?",t:"What is the time?"},
{de:"Zeitplan",ph:"TSYT-plahn (der)",en:"schedule / timetable",s:"Ich folge meinem Zeitplan.",t:"I follow my schedule."},
{de:"erste",ph:"EHR-steh",en:"first",s:"Das ist das erste Mal.",t:"This is the first time."},
{de:"letzte",ph:"LETS-teh",en:"last",s:"Das ist die letzte Chance.",t:"This is the last chance."},
{de:"nächste",ph:"NEKH-steh",en:"next",s:"Nächste Woche komme ich.",t:"I am coming next week."},
{de:"früh",ph:"FRUE",en:"early",s:"Ich muss früh aufstehen.",t:"I have to get up early."},
{de:"spät",ph:"SHPAYT",en:"late",s:"Es ist schon sehr spät.",t:"It is already very late."},
{de:"pünktlich",ph:"PUENKT-lish",en:"punctual / on time",s:"Ich bin immer pünktlich.",t:"I am always punctual."},
{de:"Vergangenheit",ph:"fehr-GAHNG-en-hyte (die)",en:"past",s:"Die Vergangenheit ist vorbei.",t:"The past is over."},
{de:"Gegenwart",ph:"GAY-gen-vart (die)",en:"present",s:"Die Gegenwart ist wichtig.",t:"The present is important."},
{de:"Zukunft",ph:"TSOO-koonft (die)",en:"future",s:"Die Zukunft ist offen.",t:"The future is open."},
{de:"Zeit",ph:"TSYTE (die)",en:"time",s:"Ich habe keine Zeit.",t:"I have no time."},
{de:"Dauer",ph:"DOW-er (die)",en:"duration",s:"Was ist die Dauer des Fluges?",t:"What is the duration of the flight?"},
{de:"schließlich",ph:"SHLEES-lish",en:"finally / in the end",s:"Schließlich hat er gewonnen.",t:"In the end he won."},
{de:"zuerst",ph:"tsoo-EHRST",en:"first of all",s:"Zuerst muss ich essen.",t:"First of all I need to eat."},
{de:"danach",ph:"dah-NAHKH",en:"after that / afterwards",s:"Danach gehe ich schlafen.",t:"After that I go to sleep."}
],

"G8 — Adjectives & Colors":[
{de:"lang",ph:"LAHNG",en:"long",s:"Der Weg ist sehr lang.",t:"The path is very long."},
{de:"kurz",ph:"KOOРTS",en:"short",s:"Das Treffen war kurz.",t:"The meeting was short."},
{de:"breit",ph:"BRYTE",en:"wide / broad",s:"Die Straße ist sehr breit.",t:"The street is very wide."},
{de:"schmal",ph:"SHMAL",en:"narrow",s:"Der Weg ist sehr schmal.",t:"The path is very narrow."},
{de:"dick",ph:"DIK",en:"thick / fat",s:"Das Buch ist sehr dick.",t:"The book is very thick."},
{de:"dünn",ph:"DUEN",en:"thin",s:"Das Papier ist sehr dünn.",t:"The paper is very thin."},
{de:"hoch",ph:"HOHKH",en:"high / tall",s:"Der Berg ist sehr hoch.",t:"The mountain is very high."},
{de:"tief",ph:"TEEF",en:"deep / low",s:"Das Wasser ist sehr tief.",t:"The water is very deep."},
{de:"neu",ph:"NOY",en:"new",s:"Ich habe ein neues Auto.",t:"I have a new car."},
{de:"alt",ph:"AHLT",en:"old",s:"Das Haus ist sehr alt.",t:"The house is very old."},
{de:"frisch",ph:"FRISH",en:"fresh",s:"Das Brot ist noch frisch.",t:"The bread is still fresh."},
{de:"fertig",ph:"FEHR-tig",en:"finished / ready",s:"Ich bin noch nicht fertig.",t:"I am not finished yet."},
{de:"leer",ph:"LEHR",en:"empty",s:"Die Flasche ist leer.",t:"The bottle is empty."},
{de:"voll",ph:"FOL",en:"full",s:"Das Glas ist voll.",t:"The glass is full."},
{de:"offen",ph:"OF-en",en:"open",s:"Das Geschäft ist offen.",t:"The shop is open."},
{de:"geschlossen",ph:"geh-SHLOS-en",en:"closed",s:"Die Bank ist geschlossen.",t:"The bank is closed."},
{de:"sauber",ph:"ZOW-ber",en:"clean",s:"Das Zimmer ist sehr sauber.",t:"The room is very clean."},
{de:"schmutzig",ph:"SHMUTZ-ig",en:"dirty",s:"Die Hände sind schmutzig.",t:"The hands are dirty."},
{de:"ganz",ph:"GAHNTS",en:"whole / complete / quite",s:"Das ist ganz normal.",t:"That is quite normal."},
{de:"halb",ph:"HAHLP",en:"half",s:"Das Glas ist halb voll.",t:"The glass is half full."},
{de:"ausgezeichnet",ph:"OWS-geh-tsykh-net",en:"excellent",s:"Die Arbeit ist ausgezeichnet.",t:"The work is excellent."},
{de:"normal",ph:"nor-MAHL",en:"normal",s:"Das ist ein normaler Tag.",t:"This is a normal day."},
{de:"besonders",ph:"beh-ZON-ders",en:"special / particularly",s:"Er ist besonders klug.",t:"He is particularly clever."},
{de:"einzigartig",ph:"INE-tsig-ahr-tig",en:"unique",s:"Dieser Ort ist einzigartig.",t:"This place is unique."},
{de:"echt",ph:"EKHT",en:"real / genuine",s:"Das ist echtes Gold.",t:"That is real gold."},
{de:"falsch",ph:"FAHLSH",en:"wrong / false",s:"Die Antwort ist falsch.",t:"The answer is wrong."},
{de:"richtig",ph:"RISH-tig",en:"correct / right",s:"Das ist richtig.",t:"That is correct."},
{de:"schnell",ph:"SHNEL",en:"fast / quick",s:"Der Zug ist sehr schnell.",t:"The train is very fast."},
{de:"langsam",ph:"LAHNG-zahm",en:"slow",s:"Fahr bitte langsam.",t:"Please drive slowly."},
{de:"stark",ph:"SHTAHRK",en:"strong",s:"Er ist sehr stark.",t:"He is very strong."},
{de:"schwach",ph:"SHVAHKH",en:"weak",s:"Ich fühle mich schwach.",t:"I feel weak."},
{de:"laut",ph:"LOWT",en:"loud",s:"Die Musik ist zu laut.",t:"The music is too loud."},
{de:"leise",ph:"LY-zeh",en:"quiet / soft",s:"Sprich bitte leise.",t:"Please speak quietly."},
{de:"hell",ph:"HEL",en:"bright / light",s:"Das Zimmer ist sehr hell.",t:"The room is very bright."},
{de:"dunkel",ph:"DOON-kel",en:"dark",s:"Es wird schnell dunkel.",t:"It gets dark quickly."},
{de:"rot",ph:"ROHT",en:"red",s:"Die Rose ist rot.",t:"The rose is red."},
{de:"blau",ph:"BLOW",en:"blue",s:"Der Himmel ist blau.",t:"The sky is blue."},
{de:"grün",ph:"GRUEN",en:"green",s:"Das Gras ist grün.",t:"The grass is green."},
{de:"gelb",ph:"GELP",en:"yellow",s:"Die Sonne ist gelb.",t:"The sun is yellow."},
{de:"schwarz",ph:"SHVAHRTS",en:"black",s:"Die Katze ist schwarz.",t:"The cat is black."},
{de:"weiß",ph:"VYSE",en:"white",s:"Der Schnee ist weiß.",t:"The snow is white."},
{de:"grau",ph:"GROW",en:"grey",s:"Der Himmel ist grau.",t:"The sky is grey."},
{de:"orange",ph:"oh-RAHN-zheh",en:"orange",s:"Die Orange ist orange.",t:"The orange is orange."},
{de:"lila",ph:"LEE-lah",en:"purple / violet",s:"Die Blume ist lila.",t:"The flower is purple."},
{de:"braun",ph:"BROWN",en:"brown",s:"Der Bär ist braun.",t:"The bear is brown."},
{de:"pink",ph:"PINK",en:"pink",s:"Das Kleid ist pink.",t:"The dress is pink."},
{de:"bunt",ph:"BOONT",en:"colourful",s:"Das Bild ist sehr bunt.",t:"The picture is very colourful."},
{de:"glücklich",ph:"GLUEK-lish",en:"happy",s:"Ich bin sehr glücklich.",t:"I am very happy."},
{de:"traurig",ph:"TROW-rig",en:"sad",s:"Sie ist heute traurig.",t:"She is sad today."},
{de:"wütend",ph:"VUE-tent",en:"angry",s:"Er ist sehr wütend.",t:"He is very angry."},
{de:"ängstlich",ph:"ENGST-lish",en:"anxious / scared",s:"Das Kind ist ängstlich.",t:"The child is anxious."},
{de:"überrascht",ph:"ue-ber-RAHSHT",en:"surprised",s:"Ich bin sehr überrascht.",t:"I am very surprised."},
{de:"entspannt",ph:"ent-SHPAHNТ",en:"relaxed",s:"Ich bin sehr entspannt.",t:"I am very relaxed."},
{de:"müde",ph:"MUE-deh",en:"tired",s:"Ich bin sehr müde.",t:"I am very tired."},
{de:"aufgeregt",ph:"OWF-geh-rehgt",en:"excited",s:"Die Kinder sind aufgeregt.",t:"The children are excited."},
{de:"stolz",ph:"SHTOLTS",en:"proud",s:"Ich bin sehr stolz.",t:"I am very proud."},
{de:"verliebt",ph:"fehr-LEEPT",en:"in love",s:"Er ist verliebt.",t:"He is in love."},
{de:"warm",ph:"VAHRM",en:"warm",s:"Das Wasser ist warm.",t:"The water is warm."},
{de:"kalt",ph:"KAHLT",en:"cold",s:"Heute ist es kalt.",t:"Today it is cold."},
{de:"heiß",ph:"HICE",en:"hot",s:"Der Kaffee ist heiß.",t:"The coffee is hot."},
{de:"kühl",ph:"KUEL",en:"cool",s:"Der Abend ist kühl.",t:"The evening is cool."},
{de:"nass",ph:"NAHS",en:"wet",s:"Meine Kleidung ist nass.",t:"My clothes are wet."},
{de:"trocken",ph:"TROK-en",en:"dry",s:"Das Handtuch ist trocken.",t:"The towel is dry."},
{de:"weich",ph:"VYKH",en:"soft",s:"Das Kissen ist weich.",t:"The pillow is soft."},
{de:"hart",ph:"HAHRT",en:"hard / tough",s:"Das Brot ist hart.",t:"The bread is hard."},
{de:"freundlich",ph:"FROYNT-lish",en:"friendly",s:"Er ist sehr freundlich.",t:"He is very friendly."},
{de:"klug",ph:"KLOOG",en:"clever / intelligent",s:"Sie ist sehr klug.",t:"She is very clever."},
{de:"ehrlich",ph:"EHR-lish",en:"honest",s:"Er ist immer ehrlich.",t:"He is always honest."},
{de:"mutig",ph:"MOO-tig",en:"brave / courageous",s:"Die Feuerwehrleute sind mutig.",t:"Firefighters are brave."},
{de:"großzügig",ph:"GROHS-tsue-gig",en:"generous",s:"Sie ist sehr großzügig.",t:"She is very generous."},
{de:"höflich",ph:"HUF-lish",en:"polite",s:"Er ist immer höflich.",t:"He is always polite."},
{de:"geduldig",ph:"geh-DOOL-dig",en:"patient",s:"Sei bitte geduldig.",t:"Please be patient."},
{de:"fleißig",ph:"FLY-sig",en:"hardworking / diligent",s:"Sie ist sehr fleißig.",t:"She is very hardworking."},
{de:"teuer",ph:"TOY-er",en:"expensive",s:"Das Hotel ist sehr teuer.",t:"The hotel is very expensive."},
{de:"billig",ph:"BIL-ig",en:"cheap",s:"Das ist sehr billig.",t:"That is very cheap."},
{de:"wichtig",ph:"VISH-tig",en:"important",s:"Das ist sehr wichtig.",t:"That is very important."},
{de:"nützlich",ph:"NUETS-lish",en:"useful",s:"Das ist sehr nützlich.",t:"That is very useful."},
{de:"möglich",ph:"MUG-lish",en:"possible",s:"Alles ist möglich.",t:"Everything is possible."},
{de:"unmöglich",ph:"oon-MUG-lish",en:"impossible",s:"Das ist unmöglich.",t:"That is impossible."},
{de:"sicher",ph:"ZISH-er",en:"safe / certain",s:"Es ist sicher so.",t:"It is certainly so."},
{de:"gefährlich",ph:"geh-FEHR-lish",en:"dangerous",s:"Das ist gefährlich.",t:"That is dangerous."},
{de:"einfach",ph:"INE-fahkh",en:"simple / easy",s:"Das ist ganz einfach.",t:"That is quite simple."},
{de:"schwierig",ph:"SHVEE-rig",en:"difficult",s:"Das ist sehr schwierig.",t:"That is very difficult."},
{de:"interessant",ph:"in-teh-reh-SAHNT",en:"interesting",s:"Das Buch ist interessant.",t:"The book is interesting."},
{de:"langweilig",ph:"LAHNG-vy-lig",en:"boring",s:"Der Film ist langweilig.",t:"The film is boring."},
{de:"lustig",ph:"LOOS-tig",en:"funny / amusing",s:"Er ist sehr lustig.",t:"He is very funny."},
{de:"traurig",ph:"TROW-rig",en:"sad",s:"Das Ende ist traurig.",t:"The ending is sad."},
{de:"schön",ph:"SHUN",en:"beautiful / nice",s:"Die Landschaft ist sehr schön.",t:"The landscape is very beautiful."},
{de:"hässlich",ph:"HES-lish",en:"ugly",s:"Das alte Gebäude ist hässlich.",t:"The old building is ugly."},
{de:"gesund",ph:"geh-ZOONT",en:"healthy",s:"Obst und Gemüse sind gesund.",t:"Fruit and vegetables are healthy."},
{de:"krank",ph:"KRAHNK",en:"ill / sick",s:"Ich bin heute krank.",t:"I am ill today."},
{de:"beliebt",ph:"beh-LEEPT",en:"popular",s:"Das Lied ist sehr beliebt.",t:"The song is very popular."},
{de:"bekannt",ph:"beh-KAHNT",en:"well-known / familiar",s:"Das ist ein bekannter Schauspieler.",t:"That is a well-known actor."}
],

"G9 — Food & Drink":[
{de:"Brot",ph:"BROHT (das)",en:"bread",s:"Ich kaufe frisches Brot.",t:"I buy fresh bread."},
{de:"Brötchen",ph:"BRUT-shen (das)",en:"bread roll",s:"Zum Frühstück esse ich Brötchen.",t:"I eat bread rolls for breakfast."},
{de:"Butter",ph:"BOOT-ter (die)",en:"butter",s:"Ich schmiere Butter aufs Brot.",t:"I spread butter on the bread."},
{de:"Mehl",ph:"MAYL (das)",en:"flour",s:"Ich brauche Mehl zum Backen.",t:"I need flour for baking."},
{de:"Reis",ph:"RYSE (der)",en:"rice",s:"Reis ist mein Lieblingsessen.",t:"Rice is my favourite food."},
{de:"Nudeln",ph:"NOO-deln (die)",en:"pasta / noodles",s:"Ich koche Nudeln mit Soße.",t:"I cook pasta with sauce."},
{de:"Kartoffel",ph:"kar-TOF-el (die)",en:"potato",s:"Deutsche lieben die Kartoffel.",t:"Germans love the potato."},
{de:"Toast",ph:"TOHST (der)",en:"toast",s:"Ich esse morgens Toast.",t:"I eat toast in the mornings."},
{de:"Milch",ph:"MILSH (die)",en:"milk",s:"Ich trinke jeden Morgen Milch.",t:"I drink milk every morning."},
{de:"Käse",ph:"KAY-zeh (der)",en:"cheese",s:"Ich mag Käse sehr gern.",t:"I like cheese very much."},
{de:"Joghurt",ph:"YOH-goort (der/das)",en:"yoghurt",s:"Zum Frühstück esse ich Joghurt.",t:"I eat yoghurt for breakfast."},
{de:"Sahne",ph:"ZAH-neh (die)",en:"cream",s:"Ich nehme Sahne in den Kaffee.",t:"I put cream in my coffee."},
{de:"Ei",ph:"EYE (das)",en:"egg",s:"Ich esse jeden Morgen ein Ei.",t:"I eat an egg every morning."},
{de:"Quark",ph:"KVARK (der)",en:"quark / curd cheese",s:"Quark ist gesund.",t:"Quark is healthy."},
{de:"Fleisch",ph:"FLYSH (das)",en:"meat",s:"Ich esse nicht viel Fleisch.",t:"I do not eat much meat."},
{de:"Hähnchen",ph:"HAYN-shen (das)",en:"chicken",s:"Heute gibt es Hähnchen.",t:"Today there is chicken."},
{de:"Rindfleisch",ph:"RINT-flysh (das)",en:"beef",s:"Das Rindfleisch ist zart.",t:"The beef is tender."},
{de:"Schweinefleisch",ph:"SHVY-neh-flysh (das)",en:"pork",s:"Schweinebraten ist lecker.",t:"Roast pork is delicious."},
{de:"Fisch",ph:"FISH (der)",en:"fish",s:"Ich esse gern Fisch.",t:"I like eating fish."},
{de:"Wurst",ph:"VOORST (die)",en:"sausage",s:"Deutschland ist berühmt für Wurst.",t:"Germany is famous for sausage."},
{de:"Schinken",ph:"SHINK-en (der)",en:"ham",s:"Ich lege Schinken aufs Brot.",t:"I put ham on the bread."},
{de:"Lachs",ph:"LAHKS (der)",en:"salmon",s:"Lachs ist sehr gesund.",t:"Salmon is very healthy."},
{de:"Tomate",ph:"toh-MAH-teh (die)",en:"tomato",s:"Die Tomate ist rot und saftig.",t:"The tomato is red and juicy."},
{de:"Gurke",ph:"GOOR-keh (die)",en:"cucumber",s:"Die Gurke ist frisch.",t:"The cucumber is fresh."},
{de:"Karotte",ph:"kah-ROT-eh (die)",en:"carrot",s:"Karotten sind gut für die Augen.",t:"Carrots are good for the eyes."},
{de:"Zwiebel",ph:"TSVEE-bel (die)",en:"onion",s:"Ich schneide die Zwiebel.",t:"I cut the onion."},
{de:"Knoblauch",ph:"KNOB-lowkh (der)",en:"garlic",s:"Knoblauch macht das Essen würzig.",t:"Garlic makes food spicy."},
{de:"Paprika",ph:"PAH-pri-kah (die/der)",en:"pepper (vegetable)",s:"Die rote Paprika ist süß.",t:"The red pepper is sweet."},
{de:"Salat",ph:"zah-LAHT (der)",en:"salad / lettuce",s:"Ich esse gern Salat.",t:"I like eating salad."},
{de:"Brokkoli",ph:"BROK-o-lee (der)",en:"broccoli",s:"Brokkoli ist sehr gesund.",t:"Broccoli is very healthy."},
{de:"Pilz",ph:"PILTS (der)",en:"mushroom",s:"Die Pilze wachsen im Wald.",t:"Mushrooms grow in the forest."},
{de:"Apfel",ph:"AHF-el (der)",en:"apple",s:"Ein Apfel am Tag.",t:"An apple a day."},
{de:"Banane",ph:"bah-NAH-neh (die)",en:"banana",s:"Die Banane ist reif.",t:"The banana is ripe."},
{de:"Orange",ph:"oh-RAHN-zheh (die)",en:"orange",s:"Ich trinke frischen Orangensaft.",t:"I drink fresh orange juice."},
{de:"Erdbeere",ph:"EHRD-bay-reh (die)",en:"strawberry",s:"Die Erdbeeren sind süß.",t:"The strawberries are sweet."},
{de:"Traube",ph:"TROW-beh (die)",en:"grape",s:"Trauben werden zu Wein.",t:"Grapes become wine."},
{de:"Kirsche",ph:"KEER-sheh (die)",en:"cherry",s:"Die Kirschen sind reif.",t:"The cherries are ripe."},
{de:"Zitrone",ph:"tsee-TROH-neh (die)",en:"lemon",s:"Die Zitrone ist sauer.",t:"The lemon is sour."},
{de:"Wasser",ph:"VAH-ser (das)",en:"water",s:"Ich trinke viel Wasser.",t:"I drink lots of water."},
{de:"Saft",ph:"ZAHFT (der)",en:"juice",s:"Ich möchte einen Saft bitte.",t:"I would like a juice please."},
{de:"Kaffee",ph:"KAH-fay (der)",en:"coffee",s:"Ich brauche morgens Kaffee.",t:"I need coffee in the mornings."},
{de:"Tee",ph:"TAY (der)",en:"tea",s:"Ich trinke lieber Tee.",t:"I prefer drinking tea."},
{de:"Bier",ph:"BEER (das)",en:"beer",s:"Ein Bier bitte!",t:"A beer please!"},
{de:"Wein",ph:"VINE (der)",en:"wine",s:"Rotwein passt gut dazu.",t:"Red wine goes well with it."},
{de:"Cola",ph:"KOH-lah (die)",en:"cola",s:"Ich möchte eine Cola.",t:"I would like a cola."},
{de:"Limonade",ph:"li-mo-NAH-deh (die)",en:"lemonade / soft drink",s:"Kinder trinken Limonade.",t:"Children drink lemonade."},
{de:"Frühstück",ph:"FRUE-shtook (das)",en:"breakfast",s:"Ich esse gern Frühstück.",t:"I like eating breakfast."},
{de:"Mittagessen",ph:"MIT-tahg-es-en (das)",en:"lunch",s:"Das Mittagessen ist fertig.",t:"Lunch is ready."},
{de:"Abendessen",ph:"AH-bent-es-en (das)",en:"dinner / supper",s:"Das Abendessen war lecker.",t:"The dinner was delicious."},
{de:"Snack",ph:"SNEK (der)",en:"snack",s:"Ich brauche einen kleinen Snack.",t:"I need a small snack."},
{de:"Dessert",ph:"deh-SEHRT (das)",en:"dessert",s:"Als Dessert gibt es Eis.",t:"For dessert there is ice cream."},
{de:"Suppe",ph:"ZOOP-eh (die)",en:"soup",s:"Die Suppe ist heiß.",t:"The soup is hot."},
{de:"Hauptgericht",ph:"HOWPT-geh-risht (das)",en:"main course",s:"Das Hauptgericht war ausgezeichnet.",t:"The main course was excellent."},
{de:"Vorspeise",ph:"FOR-shpy-zeh (die)",en:"starter",s:"Als Vorspeise nehme ich Salat.",t:"I will have salad as a starter."},
{de:"lecker",ph:"LEK-er",en:"delicious / tasty",s:"Das Essen ist sehr lecker.",t:"The food is very delicious."},
{de:"salzig",ph:"ZAHL-tsig",en:"salty",s:"Das ist zu salzig.",t:"That is too salty."},
{de:"süß",ph:"ZUESS",en:"sweet",s:"Der Kuchen ist sehr süß.",t:"The cake is very sweet."},
{de:"sauer",ph:"ZOW-er",en:"sour",s:"Die Zitrone ist sauer.",t:"The lemon is sour."},
{de:"bitter",ph:"BIT-er",en:"bitter",s:"Dieser Kaffee ist bitter.",t:"This coffee is bitter."},
{de:"scharf",ph:"SHAHRF",en:"spicy / hot",s:"Das Essen ist zu scharf.",t:"The food is too spicy."},
{de:"mild",ph:"MILT",en:"mild",s:"Die Soße ist mild.",t:"The sauce is mild."},
{de:"Speisekarte",ph:"SHPY-zeh-kar-teh (die)",en:"menu",s:"Darf ich die Speisekarte haben?",t:"May I have the menu?"},
{de:"Kellner",ph:"KEL-ner (der)",en:"waiter",s:"Der Kellner kommt gleich.",t:"The waiter is coming soon."},
{de:"bestellen",ph:"beh-SHTEL-en",en:"to order",s:"Ich möchte bestellen.",t:"I would like to order."},
{de:"Rechnung",ph:"REKH-noong (die)",en:"bill",s:"Können wir die Rechnung haben?",t:"Can we have the bill?"},
{de:"Trinkgeld",ph:"TRINK-gelt (das)",en:"tip",s:"Ich gebe Trinkgeld.",t:"I give a tip."},
{de:"Portion",ph:"por-TSEE-ohn (die)",en:"portion",s:"Die Portion ist zu groß.",t:"The portion is too big."},
{de:"vegetarisch",ph:"veh-geh-TAH-rish",en:"vegetarian",s:"Ich esse vegetarisch.",t:"I eat vegetarian."},
{de:"vegan",ph:"VAY-gahn",en:"vegan",s:"Er lebt vegan.",t:"He lives vegan."},
{de:"Rezept",ph:"reh-TSEPT (das)",en:"recipe",s:"Ich folge einem Rezept.",t:"I follow a recipe."},
{de:"Zutaten",ph:"TSOO-tah-ten (die)",en:"ingredients",s:"Die Zutaten sind frisch.",t:"The ingredients are fresh."},
{de:"Mahlzeit",ph:"MAHL-tsyte (die)",en:"meal / enjoy your meal",s:"Mahlzeit! Guten Appetit!",t:"Enjoy your meal!"},
{de:"kochen",ph:"KOH-khen",en:"to cook",s:"Ich lerne heute kochen.",t:"I am learning to cook today."},
{de:"backen",ph:"BAH-ken",en:"to bake",s:"Ich will einen Kuchen backen.",t:"I want to bake a cake."},
{de:"braten",ph:"BRAH-ten",en:"to fry / roast",s:"Wir braten das Hähnchen.",t:"We roast the chicken."},
{de:"schneiden",ph:"SHNY-den",en:"to cut",s:"Ich schneide das Gemüse.",t:"I cut the vegetables."},
{de:"würzen",ph:"VUER-tsen",en:"to season",s:"Ich würze die Suppe.",t:"I season the soup."},
{de:"schmecken",ph:"SHMEK-en",en:"to taste",s:"Das schmeckt wunderbar.",t:"That tastes wonderful."},
{de:"Hunger",ph:"HOONG-er (der)",en:"hunger",s:"Ich habe großen Hunger.",t:"I am very hungry."},
{de:"Durst",ph:"DOORST (der)",en:"thirst",s:"Ich habe Durst.",t:"I am thirsty."},
{de:"essen",ph:"ES-en",en:"to eat",s:"Wir essen zusammen.",t:"We eat together."},
{de:"trinken",ph:"TRINK-en",en:"to drink",s:"Was möchtest du trinken?",t:"What would you like to drink?"},
{de:"Mahlzeit",ph:"MAHL-tsyte",en:"mealtime",s:"Es ist Mahlzeit.",t:"It is mealtime."},
{de:"Kuchen",ph:"KOO-khen (der)",en:"cake",s:"Der Kuchen ist frisch gebacken.",t:"The cake is freshly baked."},
{de:"Eis",ph:"ICE (das)",en:"ice cream / ice",s:"Im Sommer esse ich Eis.",t:"In summer I eat ice cream."},
{de:"Schokolade",ph:"sho-ko-LAH-deh (die)",en:"chocolate",s:"Ich liebe dunkle Schokolade.",t:"I love dark chocolate."},
{de:"Zucker",ph:"TSOOK-er (der)",en:"sugar",s:"Ich nehme keinen Zucker.",t:"I do not take sugar."},
{de:"Salz",ph:"ZAHLTS (das)",en:"salt",s:"Zu viel Salz ist ungesund.",t:"Too much salt is unhealthy."}
],

"G10 — Grammar Words":[
{de:"der",ph:"DEHR",en:"the (masculine nominative)",s:"Der Mann ist groß.",t:"The man is tall."},
{de:"die",ph:"DEE",en:"the (feminine / plural)",s:"Die Frau lacht.",t:"The woman laughs."},
{de:"das",ph:"DAHS",en:"the (neuter)",s:"Das Kind schläft.",t:"The child is sleeping."},
{de:"den",ph:"DEHN",en:"the (masculine accusative)",s:"Ich sehe den Mann.",t:"I see the man."},
{de:"dem",ph:"DEHM",en:"the (dative)",s:"Ich gebe dem Mann das Buch.",t:"I give the man the book."},
{de:"des",ph:"DES",en:"the (genitive)",s:"Das Auto des Mannes ist rot.",t:"The man's car is red."},
{de:"ein",ph:"INE",en:"a / an (masculine/neuter)",s:"Das ist ein Hund.",t:"That is a dog."},
{de:"eine",ph:"INE-eh",en:"a / an (feminine)",s:"Das ist eine Katze.",t:"That is a cat."},
{de:"einen",ph:"INE-en",en:"a / an (masculine accusative)",s:"Ich sehe einen Vogel.",t:"I see a bird."},
{de:"kein",ph:"KINE",en:"no / not a (masculine/neuter)",s:"Das ist kein Problem.",t:"That is no problem."},
{de:"keine",ph:"KY-neh",en:"no / not a (feminine/plural)",s:"Ich habe keine Zeit.",t:"I have no time."},
{de:"mein",ph:"MINE",en:"my (masculine/neuter)",s:"Das ist mein Buch.",t:"That is my book."},
{de:"meine",ph:"MY-neh",en:"my (feminine/plural)",s:"Das ist meine Schwester.",t:"That is my sister."},
{de:"dein",ph:"DINE",en:"your (informal, masc/neut)",s:"Ist das dein Auto?",t:"Is that your car?"},
{de:"deine",ph:"DY-neh",en:"your (informal, fem/plural)",s:"Das ist deine Tasche.",t:"That is your bag."},
{de:"sein",ph:"ZINE",en:"his",s:"Das ist sein Haus.",t:"That is his house."},
{de:"ihre",ph:"EE-reh",en:"her / their",s:"Das ist ihre Mutter.",t:"That is her mother."},
{de:"unser",ph:"OON-zer",en:"our",s:"Das ist unser Auto.",t:"That is our car."},
{de:"euer",ph:"OY-er",en:"your (plural)",s:"Das ist euer Haus.",t:"That is your house."},
{de:"dieser",ph:"DEE-zer",en:"this (masc)",s:"Dieser Mann ist nett.",t:"This man is nice."},
{de:"diese",ph:"DEE-zeh",en:"this (fem/plural)",s:"Diese Frau ist klug.",t:"This woman is clever."},
{de:"dieses",ph:"DEE-zes",en:"this (neuter)",s:"Dieses Kind ist müde.",t:"This child is tired."},
{de:"jeder",ph:"YAY-der",en:"every / each",s:"Jeder Mensch ist wichtig.",t:"Every person is important."},
{de:"alle",ph:"AHL-eh",en:"all",s:"Alle Kinder spielen.",t:"All children play."},
{de:"beide",ph:"BY-deh",en:"both",s:"Beide Antworten stimmen.",t:"Both answers are correct."},
{de:"viele",ph:"FEE-leh",en:"many",s:"Viele Leute kommen.",t:"Many people come."},
{de:"einige",ph:"INE-ih-geh",en:"some / a few",s:"Einige Studenten fehlen.",t:"Some students are absent."},
{de:"manche",ph:"MAHN-kheh",en:"some / certain",s:"Manche Leute lieben Sport.",t:"Some people love sport."},
{de:"in",ph:"IN",en:"in / into",s:"Ich bin in der Küche.",t:"I am in the kitchen."},
{de:"an",ph:"AHN",en:"at / on (vertical surface)",s:"Das Bild hängt an der Wand.",t:"The picture hangs on the wall."},
{de:"auf",ph:"OWF",en:"on (horizontal) / onto",s:"Das Buch liegt auf dem Tisch.",t:"The book is on the table."},
{de:"unter",ph:"OON-ter",en:"under / below",s:"Die Katze liegt unter dem Tisch.",t:"The cat lies under the table."},
{de:"über",ph:"UE-ber",en:"over / above / about",s:"Das Flugzeug fliegt über uns.",t:"The aeroplane flies over us."},
{de:"vor",ph:"FOHR",en:"in front of / before",s:"Er steht vor dem Haus.",t:"He stands in front of the house."},
{de:"hinter",ph:"HIN-ter",en:"behind",s:"Der Hund ist hinter dem Haus.",t:"The dog is behind the house."},
{de:"neben",ph:"NAY-ben",en:"next to / beside",s:"Ich sitze neben ihm.",t:"I sit beside him."},
{de:"zwischen",ph:"TSVISH-en",en:"between",s:"Das Café ist zwischen zwei Läden.",t:"The café is between two shops."},
{de:"gegenüber",ph:"GAY-gen-ue-ber",en:"opposite",s:"Die Bank ist gegenüber dem Park.",t:"The bank is opposite the park."},
{de:"durch",ph:"DOORKH",en:"through",s:"Ich gehe durch den Park.",t:"I walk through the park."},
{de:"mit",ph:"MIT",en:"with",s:"Ich komme mit dir.",t:"I am coming with you."},
{de:"ohne",ph:"OH-neh",en:"without",s:"Ich trinke Kaffee ohne Zucker.",t:"I drink coffee without sugar."},
{de:"für",ph:"FUER",en:"for",s:"Das ist für dich.",t:"That is for you."},
{de:"gegen",ph:"GAY-gen",en:"against",s:"Er ist gegen die Idee.",t:"He is against the idea."},
{de:"um",ph:"OOM",en:"around / at (time)",s:"Wir treffen uns um drei.",t:"We meet at three."},
{de:"bei",ph:"BY",en:"at / near / with",s:"Ich wohne bei meinen Eltern.",t:"I live with my parents."},
{de:"seit",ph:"ZYTE",en:"since / for (time)",s:"Ich lerne seit einem Jahr Deutsch.",t:"I have been learning German for a year."},
{de:"nach",ph:"NAHKH",en:"after / to (place)",s:"Ich fahre nach Berlin.",t:"I am going to Berlin."},
{de:"von",ph:"FON",en:"from / of",s:"Das ist ein Geschenk von mir.",t:"That is a gift from me."},
{de:"zu",ph:"TSOO",en:"to / too",s:"Ich gehe zu Hause.",t:"I am going home."},
{de:"aus",ph:"OWS",en:"from / out of",s:"Ich komme aus Deutschland.",t:"I come from Germany."},
{de:"bis",ph:"BIS",en:"until / up to",s:"Ich warte bis morgen.",t:"I wait until tomorrow."},
{de:"ab",ph:"AHP",en:"from (time) / off",s:"Ab morgen lerne ich mehr.",t:"From tomorrow I will learn more."},
{de:"wegen",ph:"VAY-gen",en:"because of",s:"Wegen des Regens bleibe ich.",t:"Because of the rain I am staying."},
{de:"während",ph:"VEH-rent",en:"during / while",s:"Während des Essens reden wir.",t:"We talk during the meal."},
{de:"trotz",ph:"TROTS",en:"despite",s:"Trotz des Regens gehe ich.",t:"Despite the rain I go."},
{de:"statt",ph:"SHTAHT",en:"instead of",s:"Statt Kaffee trinke ich Tee.",t:"Instead of coffee I drink tea."},
{de:"außer",ph:"OWS-er",en:"except / besides",s:"Alle außer mir kommen.",t:"Everyone except me is coming."},
{de:"damit",ph:"dah-MIT",en:"so that / with it",s:"Ich lerne, damit ich Arbeit finde.",t:"I study so that I find work."},
{de:"falls",ph:"FAHLS",en:"in case / if",s:"Falls es regnet, bleibe ich.",t:"In case it rains, I will stay."},
{de:"obwohl",ph:"ob-VOHL",en:"although",s:"Obwohl es kalt ist, gehe ich.",t:"Although it is cold, I am going."},
{de:"während",ph:"VEH-rent",en:"while / whereas",s:"Während er schläft, arbeite ich.",t:"While he sleeps, I work."},
{de:"doch",ph:"DOKH",en:"yet / but / indeed",s:"Das ist doch nicht wahr!",t:"That is indeed not true!"},
{de:"mal",ph:"MAHL",en:"just / once (softener)",s:"Komm mal hier.",t:"Come here a moment."},
{de:"eben",ph:"AY-ben",en:"just / exactly / flat",s:"Das ist eben so.",t:"That is just how it is."},
{de:"eigentlich",ph:"EYE-gent-lish",en:"actually / really",s:"Ich wollte eigentlich schlafen.",t:"I actually wanted to sleep."},
{de:"nämlich",ph:"NAYM-lish",en:"namely / you see",s:"Er kommt nicht, nämlich er ist krank.",t:"He is not coming, you see he is ill."},
{de:"wohl",ph:"VOHL",en:"probably / well",s:"Er ist wohl krank.",t:"He is probably ill."},
{de:"gerade",ph:"geh-RAH-deh",en:"just / straight",s:"Ich bin gerade angekommen.",t:"I have just arrived."},
{de:"sogar",ph:"zoh-GAHR",en:"even",s:"Sogar er versteht das.",t:"Even he understands that."},
{de:"fast",ph:"FAHST",en:"almost / nearly",s:"Es ist fast fertig.",t:"It is almost ready."},
{de:"kaum",ph:"KOWM",en:"hardly / barely",s:"Ich kann kaum glauben.",t:"I can hardly believe it."},
{de:"bereits",ph:"beh-RYTS",en:"already",s:"Er ist bereits da.",t:"He is already there."},
{de:"noch nicht",ph:"NOKH NISHT",en:"not yet",s:"Ich bin noch nicht bereit.",t:"I am not yet ready."},
{de:"gar nicht",ph:"GAHR NISHT",en:"not at all",s:"Das stimmt gar nicht.",t:"That is not true at all."},
{de:"zwar",ph:"TSVAHR",en:"it is true that / admittedly",s:"Das ist zwar schwer, aber möglich.",t:"It is admittedly hard but possible."},
{de:"außerdem",ph:"OWS-er-dem",en:"moreover / besides",s:"Außerdem ist er müde.",t:"Moreover he is tired."},
{de:"jedoch",ph:"yeh-DOKH",en:"however / yet",s:"Ich wollte kommen, jedoch hatte ich keine Zeit.",t:"I wanted to come, however I had no time."},
{de:"deshalb",ph:"DES-hahlp",en:"therefore / that is why",s:"Es regnet, deshalb bleibe ich.",t:"It is raining, that is why I stay."},
{de:"zum Beispiel",ph:"tsoom BY-shpeel",en:"for example",s:"Zum Beispiel esse ich Obst.",t:"For example I eat fruit."},
{de:"im Gegenteil",ph:"im GAY-gen-tile",en:"on the contrary",s:"Im Gegenteil, ich mag das.",t:"On the contrary, I like that."},
{de:"auf jeden Fall",ph:"owf YAY-den fahl",en:"in any case",s:"Auf jeden Fall komme ich.",t:"In any case I will come."},
{de:"zum Glück",ph:"tsoom GLUEK",en:"fortunately / luckily",s:"Zum Glück hat es aufgehört.",t:"Fortunately it has stopped."},
{de:"leider",ph:"LY-der",en:"unfortunately",s:"Leider kann ich nicht kommen.",t:"Unfortunately I cannot come."},
{de:"hoffentlich",ph:"HOF-ent-lish",en:"hopefully",s:"Hoffentlich klappt es.",t:"Hopefully it will work out."},
{de:"wahrscheinlich",ph:"vahr-SHYNE-lish",en:"probably / likely",s:"Er kommt wahrscheinlich morgen.",t:"He will probably come tomorrow."},
{de:"vielleicht",ph:"fee-LYSHT",en:"maybe / perhaps",s:"Vielleicht hat er Recht.",t:"Maybe he is right."},
{de:"bestimmt",ph:"beh-SHTIMMT",en:"definitely / certainly",s:"Er kommt bestimmt.",t:"He is definitely coming."},
{de:"ungefähr",ph:"oon-geh-FEHR",en:"approximately",s:"Es dauert ungefähr eine Stunde.",t:"It takes approximately one hour."},
{de:"mindestens",ph:"MIN-des-tens",en:"at least",s:"Ich brauche mindestens zwei Stunden.",t:"I need at least two hours."},
{de:"höchstens",ph:"HUKH-stens",en:"at most",s:"Es dauert höchstens eine Stunde.",t:"It takes at most one hour."},
{de:"zusammen",ph:"tsoo-ZAHM-en",en:"together",s:"Wir machen das zusammen.",t:"We do that together."},
{de:"allein",ph:"ah-LINE",en:"alone",s:"Ich bin allein.",t:"I am alone."},
{de:"gegenseitig",ph:"GAY-gen-zy-tig",en:"mutual / each other",s:"Wir helfen uns gegenseitig.",t:"We help each other."}
]

}); // end Object.assign — all 10 groups loaded
